import type { MappingData } from './mapping_data.js'

export const buttons: MappingData[] = [
	{
		id: 'Macro__Apply',
		label: 'Macro - Apply',
		channel: 0,
		number: 0,
		velocity: 42,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'physical',
	},
	{
		id: 'Macro__Clear Apply',
		label: 'Macro - Clear Apply',
		channel: 0,
		number: 0,
		velocity: 43,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'physical',
	},
	{
		id: 'Effect__Confetti',
		label: 'Effect - Confetti',
		channel: 0,
		number: 0,
		velocity: 79,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'Effect__Co2 Down',
		label: 'Effect - Co2 Down',
		channel: 0,
		number: 0,
		velocity: 80,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'Effect__Co2 Up',
		label: 'Effect - Co2 Up',
		channel: 0,
		number: 0,
		velocity: 81,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'Effect__Fire',
		label: 'Effect - Fire',
		channel: 0,
		number: 0,
		velocity: 82,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'Effect__Bubbles',
		label: 'Effect - Bubbles',
		channel: 0,
		number: 0,
		velocity: 83,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'Effect__Reset',
		label: 'Effect - Reset',
		channel: 0,
		number: 0,
		velocity: 84,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'Midi Only__Write `[Neoluma][Midi] Pong` to Log, if Ready',
		label: 'Midi Only - Write `[Neoluma][Midi] Pong` to Log, if Ready',
		channel: 0,
		number: 1,
		velocity: 20,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'midi',
	},
	{
		id: 'Advanced__Force Resync All',
		label: 'Advanced - Force Resync All',
		channel: 0,
		number: 1,
		velocity: 57,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'AudioLink__Reset Settings',
		label: 'AudioLink - Reset Settings',
		channel: 0,
		number: 1,
		velocity: 115,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'AudioLink Smoothing__Reset Settings',
		label: 'AudioLink Smoothing - Reset Settings',
		channel: 0,
		number: 1,
		velocity: 116,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'General__UI Larger',
		label: 'General - UI Larger',
		channel: 0,
		number: 1,
		velocity: 117,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'physical',
	},
	{
		id: 'General__UI Smaller',
		label: 'General - UI Smaller',
		channel: 0,
		number: 1,
		velocity: 118,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'physical',
	},
	{
		id: 'Midi Only__Dump All State as Feedback',
		label: 'Midi Only - Dump All State as Feedback',
		channel: 0,
		number: 1,
		velocity: 121,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'midi',
	},
	{
		id: 'Macro__Macro',
		label: 'Macro - Macro',
		isLogical: false,
		type: 'indexed',
		enum: null,
		class: 'physical',
		values: [
			{
				id: '0',
				label: '0',
				channel: 0,
				number: 0,
				velocity: 47,
				type: 'single',
			},
			{
				id: '1',
				label: '1',
				channel: 0,
				number: 0,
				velocity: 48,
				type: 'single',
			},
			{
				id: '2',
				label: '2',
				channel: 0,
				number: 0,
				velocity: 49,
				type: 'single',
			},
			{
				id: '3',
				label: '3',
				channel: 0,
				number: 0,
				velocity: 50,
				type: 'single',
			},
			{
				id: '4',
				label: '4',
				channel: 0,
				number: 0,
				velocity: 51,
				type: 'single',
			},
			{
				id: '5',
				label: '5',
				channel: 0,
				number: 0,
				velocity: 52,
				type: 'single',
			},
			{
				id: '6',
				label: '6',
				channel: 0,
				number: 0,
				velocity: 53,
				type: 'single',
			},
			{
				id: '7',
				label: '7',
				channel: 0,
				number: 0,
				velocity: 54,
				type: 'single',
			},
			{
				id: '8',
				label: '8',
				channel: 0,
				number: 0,
				velocity: 55,
				type: 'single',
			},
			{
				id: '9',
				label: '9',
				channel: 0,
				number: 0,
				velocity: 56,
				type: 'single',
			},
			{
				id: '10',
				label: '10',
				channel: 0,
				number: 0,
				velocity: 57,
				type: 'single',
			},
			{
				id: '11',
				label: '11',
				channel: 0,
				number: 0,
				velocity: 58,
				type: 'single',
			},
			{
				id: '12',
				label: '12',
				channel: 0,
				number: 0,
				velocity: 59,
				type: 'single',
			},
			{
				id: '13',
				label: '13',
				channel: 0,
				number: 0,
				velocity: 60,
				type: 'single',
			},
			{
				id: '14',
				label: '14',
				channel: 0,
				number: 0,
				velocity: 61,
				type: 'single',
			},
			{
				id: '15',
				label: '15',
				channel: 0,
				number: 0,
				velocity: 62,
				type: 'single',
			},
			{
				id: '16',
				label: '16',
				channel: 0,
				number: 0,
				velocity: 63,
				type: 'single',
			},
			{
				id: '17',
				label: '17',
				channel: 0,
				number: 0,
				velocity: 64,
				type: 'single',
			},
			{
				id: '18',
				label: '18',
				channel: 0,
				number: 0,
				velocity: 65,
				type: 'single',
			},
			{
				id: '19',
				label: '19',
				channel: 0,
				number: 0,
				velocity: 66,
				type: 'single',
			},
			{
				id: '20',
				label: '20',
				channel: 0,
				number: 0,
				velocity: 67,
				type: 'single',
			},
			{
				id: '21',
				label: '21',
				channel: 0,
				number: 0,
				velocity: 68,
				type: 'single',
			},
			{
				id: '22',
				label: '22',
				channel: 0,
				number: 0,
				velocity: 69,
				type: 'single',
			},
			{
				id: '23',
				label: '23',
				channel: 0,
				number: 0,
				velocity: 70,
				type: 'single',
			},
			{
				id: '24',
				label: '24',
				channel: 0,
				number: 0,
				velocity: 71,
				type: 'single',
			},
			{
				id: '25',
				label: '25',
				channel: 0,
				number: 0,
				velocity: 72,
				type: 'single',
			},
			{
				id: '26',
				label: '26',
				channel: 0,
				number: 0,
				velocity: 73,
				type: 'single',
			},
			{
				id: '27',
				label: '27',
				channel: 0,
				number: 0,
				velocity: 74,
				type: 'single',
			},
			{
				id: '28',
				label: '28',
				channel: 0,
				number: 0,
				velocity: 75,
				type: 'single',
			},
			{
				id: '29',
				label: '29',
				channel: 0,
				number: 0,
				velocity: 76,
				type: 'single',
			},
			{
				id: '30',
				label: '30',
				channel: 0,
				number: 0,
				velocity: 77,
				type: 'single',
			},
			{
				id: '31',
				label: '31',
				channel: 0,
				number: 0,
				velocity: 78,
				type: 'single',
			},
		],
	},
	{
		id: 'General__Color',
		label: 'General - Color',
		isLogical: false,
		type: 'indexed',
		enum: null,
		class: 'physical',
		values: [
			{
				id: '0',
				label: '0',
				channel: 0,
				number: 1,
				velocity: 4,
				type: 'single',
			},
			{
				id: '1',
				label: '1',
				channel: 0,
				number: 1,
				velocity: 5,
				type: 'single',
			},
			{
				id: '2',
				label: '2',
				channel: 0,
				number: 1,
				velocity: 6,
				type: 'single',
			},
			{
				id: '3',
				label: '3',
				channel: 0,
				number: 1,
				velocity: 7,
				type: 'single',
			},
			{
				id: '4',
				label: '4',
				channel: 0,
				number: 1,
				velocity: 8,
				type: 'single',
			},
			{
				id: '5',
				label: '5',
				channel: 0,
				number: 1,
				velocity: 9,
				type: 'single',
			},
			{
				id: '6',
				label: '6',
				channel: 0,
				number: 1,
				velocity: 10,
				type: 'single',
			},
			{
				id: '7',
				label: '7',
				channel: 0,
				number: 1,
				velocity: 11,
				type: 'single',
			},
			{
				id: '8',
				label: '8',
				channel: 0,
				number: 1,
				velocity: 12,
				type: 'single',
			},
			{
				id: '9',
				label: '9',
				channel: 0,
				number: 1,
				velocity: 13,
				type: 'single',
			},
			{
				id: '10',
				label: '10',
				channel: 0,
				number: 1,
				velocity: 14,
				type: 'single',
			},
			{
				id: '11',
				label: '11',
				channel: 0,
				number: 1,
				velocity: 15,
				type: 'single',
			},
			{
				id: '12',
				label: '12',
				channel: 0,
				number: 1,
				velocity: 16,
				type: 'single',
			},
			{
				id: '13',
				label: '13',
				channel: 0,
				number: 1,
				velocity: 17,
				type: 'single',
			},
			{
				id: '14',
				label: '14',
				channel: 0,
				number: 1,
				velocity: 18,
				type: 'single',
			},
			{
				id: '15',
				label: '15',
				channel: 0,
				number: 1,
				velocity: 19,
				type: 'single',
			},
		],
	},
	{
		id: 'Macro__Use Macro',
		label: 'Macro - Use Macro',
		isLogical: false,
		type: 'indexed',
		enum: null,
		class: 'logical',
		values: [
			{
				id: '0',
				label: '0',
				channel: 0,
				number: 37,
				velocity: 0,
				type: 'single',
			},
			{
				id: '1',
				label: '1',
				channel: 0,
				number: 37,
				velocity: 1,
				type: 'single',
			},
			{
				id: '2',
				label: '2',
				channel: 0,
				number: 37,
				velocity: 2,
				type: 'single',
			},
			{
				id: '3',
				label: '3',
				channel: 0,
				number: 37,
				velocity: 3,
				type: 'single',
			},
			{
				id: '4',
				label: '4',
				channel: 0,
				number: 37,
				velocity: 4,
				type: 'single',
			},
			{
				id: '5',
				label: '5',
				channel: 0,
				number: 37,
				velocity: 5,
				type: 'single',
			},
			{
				id: '6',
				label: '6',
				channel: 0,
				number: 37,
				velocity: 6,
				type: 'single',
			},
			{
				id: '7',
				label: '7',
				channel: 0,
				number: 37,
				velocity: 7,
				type: 'single',
			},
			{
				id: '8',
				label: '8',
				channel: 0,
				number: 37,
				velocity: 8,
				type: 'single',
			},
			{
				id: '9',
				label: '9',
				channel: 0,
				number: 37,
				velocity: 9,
				type: 'single',
			},
			{
				id: '10',
				label: '10',
				channel: 0,
				number: 37,
				velocity: 10,
				type: 'single',
			},
			{
				id: '11',
				label: '11',
				channel: 0,
				number: 37,
				velocity: 11,
				type: 'single',
			},
			{
				id: '12',
				label: '12',
				channel: 0,
				number: 37,
				velocity: 12,
				type: 'single',
			},
			{
				id: '13',
				label: '13',
				channel: 0,
				number: 37,
				velocity: 13,
				type: 'single',
			},
			{
				id: '14',
				label: '14',
				channel: 0,
				number: 37,
				velocity: 14,
				type: 'single',
			},
			{
				id: '15',
				label: '15',
				channel: 0,
				number: 37,
				velocity: 15,
				type: 'single',
			},
			{
				id: '16',
				label: '16',
				channel: 0,
				number: 37,
				velocity: 16,
				type: 'single',
			},
			{
				id: '17',
				label: '17',
				channel: 0,
				number: 37,
				velocity: 17,
				type: 'single',
			},
			{
				id: '18',
				label: '18',
				channel: 0,
				number: 37,
				velocity: 18,
				type: 'single',
			},
			{
				id: '19',
				label: '19',
				channel: 0,
				number: 37,
				velocity: 19,
				type: 'single',
			},
			{
				id: '20',
				label: '20',
				channel: 0,
				number: 37,
				velocity: 20,
				type: 'single',
			},
			{
				id: '21',
				label: '21',
				channel: 0,
				number: 37,
				velocity: 21,
				type: 'single',
			},
			{
				id: '22',
				label: '22',
				channel: 0,
				number: 37,
				velocity: 22,
				type: 'single',
			},
			{
				id: '23',
				label: '23',
				channel: 0,
				number: 37,
				velocity: 23,
				type: 'single',
			},
			{
				id: '24',
				label: '24',
				channel: 0,
				number: 37,
				velocity: 24,
				type: 'single',
			},
			{
				id: '25',
				label: '25',
				channel: 0,
				number: 37,
				velocity: 25,
				type: 'single',
			},
			{
				id: '26',
				label: '26',
				channel: 0,
				number: 37,
				velocity: 26,
				type: 'single',
			},
			{
				id: '27',
				label: '27',
				channel: 0,
				number: 37,
				velocity: 27,
				type: 'single',
			},
			{
				id: '28',
				label: '28',
				channel: 0,
				number: 37,
				velocity: 28,
				type: 'single',
			},
			{
				id: '29',
				label: '29',
				channel: 0,
				number: 37,
				velocity: 29,
				type: 'single',
			},
			{
				id: '30',
				label: '30',
				channel: 0,
				number: 37,
				velocity: 30,
				type: 'single',
			},
			{
				id: '31',
				label: '31',
				channel: 0,
				number: 37,
				velocity: 31,
				type: 'single',
			},
		],
	},
	{
		id: 'Macro__Set Macro',
		label: 'Macro - Set Macro',
		isLogical: false,
		type: 'indexed',
		enum: null,
		class: 'logical',
		values: [
			{
				id: '0',
				label: '0',
				channel: 0,
				number: 37,
				velocity: 32,
				type: 'single',
			},
			{
				id: '1',
				label: '1',
				channel: 0,
				number: 37,
				velocity: 33,
				type: 'single',
			},
			{
				id: '2',
				label: '2',
				channel: 0,
				number: 37,
				velocity: 34,
				type: 'single',
			},
			{
				id: '3',
				label: '3',
				channel: 0,
				number: 37,
				velocity: 35,
				type: 'single',
			},
			{
				id: '4',
				label: '4',
				channel: 0,
				number: 37,
				velocity: 36,
				type: 'single',
			},
			{
				id: '5',
				label: '5',
				channel: 0,
				number: 37,
				velocity: 37,
				type: 'single',
			},
			{
				id: '6',
				label: '6',
				channel: 0,
				number: 37,
				velocity: 38,
				type: 'single',
			},
			{
				id: '7',
				label: '7',
				channel: 0,
				number: 37,
				velocity: 39,
				type: 'single',
			},
			{
				id: '8',
				label: '8',
				channel: 0,
				number: 37,
				velocity: 40,
				type: 'single',
			},
			{
				id: '9',
				label: '9',
				channel: 0,
				number: 37,
				velocity: 41,
				type: 'single',
			},
			{
				id: '10',
				label: '10',
				channel: 0,
				number: 37,
				velocity: 42,
				type: 'single',
			},
			{
				id: '11',
				label: '11',
				channel: 0,
				number: 37,
				velocity: 43,
				type: 'single',
			},
			{
				id: '12',
				label: '12',
				channel: 0,
				number: 37,
				velocity: 44,
				type: 'single',
			},
			{
				id: '13',
				label: '13',
				channel: 0,
				number: 37,
				velocity: 45,
				type: 'single',
			},
			{
				id: '14',
				label: '14',
				channel: 0,
				number: 37,
				velocity: 46,
				type: 'single',
			},
			{
				id: '15',
				label: '15',
				channel: 0,
				number: 37,
				velocity: 47,
				type: 'single',
			},
			{
				id: '16',
				label: '16',
				channel: 0,
				number: 37,
				velocity: 48,
				type: 'single',
			},
			{
				id: '17',
				label: '17',
				channel: 0,
				number: 37,
				velocity: 49,
				type: 'single',
			},
			{
				id: '18',
				label: '18',
				channel: 0,
				number: 37,
				velocity: 50,
				type: 'single',
			},
			{
				id: '19',
				label: '19',
				channel: 0,
				number: 37,
				velocity: 51,
				type: 'single',
			},
			{
				id: '20',
				label: '20',
				channel: 0,
				number: 37,
				velocity: 52,
				type: 'single',
			},
			{
				id: '21',
				label: '21',
				channel: 0,
				number: 37,
				velocity: 53,
				type: 'single',
			},
			{
				id: '22',
				label: '22',
				channel: 0,
				number: 37,
				velocity: 54,
				type: 'single',
			},
			{
				id: '23',
				label: '23',
				channel: 0,
				number: 37,
				velocity: 55,
				type: 'single',
			},
			{
				id: '24',
				label: '24',
				channel: 0,
				number: 37,
				velocity: 56,
				type: 'single',
			},
			{
				id: '25',
				label: '25',
				channel: 0,
				number: 37,
				velocity: 57,
				type: 'single',
			},
			{
				id: '26',
				label: '26',
				channel: 0,
				number: 37,
				velocity: 58,
				type: 'single',
			},
			{
				id: '27',
				label: '27',
				channel: 0,
				number: 37,
				velocity: 59,
				type: 'single',
			},
			{
				id: '28',
				label: '28',
				channel: 0,
				number: 37,
				velocity: 60,
				type: 'single',
			},
			{
				id: '29',
				label: '29',
				channel: 0,
				number: 37,
				velocity: 61,
				type: 'single',
			},
			{
				id: '30',
				label: '30',
				channel: 0,
				number: 37,
				velocity: 62,
				type: 'single',
			},
			{
				id: '31',
				label: '31',
				channel: 0,
				number: 37,
				velocity: 63,
				type: 'single',
			},
		],
	},
	{
		id: 'General__Set Color',
		label: 'General - Set Color',
		isLogical: false,
		type: 'indexed',
		enum: null,
		class: 'logical',
		values: [
			{
				id: '0',
				label: '0',
				channel: 0,
				number: 56,
				velocity: 64,
				type: 'single',
			},
			{
				id: '1',
				label: '1',
				channel: 0,
				number: 56,
				velocity: 65,
				type: 'single',
			},
			{
				id: '2',
				label: '2',
				channel: 0,
				number: 56,
				velocity: 66,
				type: 'single',
			},
			{
				id: '3',
				label: '3',
				channel: 0,
				number: 56,
				velocity: 67,
				type: 'single',
			},
			{
				id: '4',
				label: '4',
				channel: 0,
				number: 56,
				velocity: 68,
				type: 'single',
			},
			{
				id: '5',
				label: '5',
				channel: 0,
				number: 56,
				velocity: 69,
				type: 'single',
			},
			{
				id: '6',
				label: '6',
				channel: 0,
				number: 56,
				velocity: 70,
				type: 'single',
			},
			{
				id: '7',
				label: '7',
				channel: 0,
				number: 56,
				velocity: 71,
				type: 'single',
			},
			{
				id: '8',
				label: '8',
				channel: 0,
				number: 56,
				velocity: 72,
				type: 'single',
			},
			{
				id: '9',
				label: '9',
				channel: 0,
				number: 56,
				velocity: 73,
				type: 'single',
			},
			{
				id: '10',
				label: '10',
				channel: 0,
				number: 56,
				velocity: 74,
				type: 'single',
			},
			{
				id: '11',
				label: '11',
				channel: 0,
				number: 56,
				velocity: 75,
				type: 'single',
			},
			{
				id: '12',
				label: '12',
				channel: 0,
				number: 56,
				velocity: 76,
				type: 'single',
			},
			{
				id: '13',
				label: '13',
				channel: 0,
				number: 56,
				velocity: 77,
				type: 'single',
			},
			{
				id: '14',
				label: '14',
				channel: 0,
				number: 56,
				velocity: 78,
				type: 'single',
			},
			{
				id: '15',
				label: '15',
				channel: 0,
				number: 56,
				velocity: 79,
				type: 'single',
			},
			{
				id: '16',
				label: '16',
				channel: 0,
				number: 56,
				velocity: 80,
				type: 'single',
			},
			{
				id: '17',
				label: '17',
				channel: 0,
				number: 56,
				velocity: 81,
				type: 'single',
			},
			{
				id: '18',
				label: '18',
				channel: 0,
				number: 56,
				velocity: 82,
				type: 'single',
			},
			{
				id: '19',
				label: '19',
				channel: 0,
				number: 56,
				velocity: 83,
				type: 'single',
			},
			{
				id: '20',
				label: '20',
				channel: 0,
				number: 56,
				velocity: 84,
				type: 'single',
			},
			{
				id: '21',
				label: '21',
				channel: 0,
				number: 56,
				velocity: 85,
				type: 'single',
			},
			{
				id: '22',
				label: '22',
				channel: 0,
				number: 56,
				velocity: 86,
				type: 'single',
			},
			{
				id: '23',
				label: '23',
				channel: 0,
				number: 56,
				velocity: 87,
				type: 'single',
			},
		],
	},
	{
		id: 'General__Gobo',
		label: 'General - Gobo',
		isLogical: false,
		type: 'indexed',
		enum: null,
		class: 'physical',
		values: [
			{
				id: '0',
				label: '0',
				channel: 0,
				number: 1,
				velocity: 40,
				type: 'single',
			},
			{
				id: '1',
				label: '1',
				channel: 0,
				number: 1,
				velocity: 41,
				type: 'single',
			},
			{
				id: '2',
				label: '2',
				channel: 0,
				number: 1,
				velocity: 42,
				type: 'single',
			},
			{
				id: '3',
				label: '3',
				channel: 0,
				number: 1,
				velocity: 43,
				type: 'single',
			},
			{
				id: '4',
				label: '4',
				channel: 0,
				number: 1,
				velocity: 44,
				type: 'single',
			},
			{
				id: '5',
				label: '5',
				channel: 0,
				number: 1,
				velocity: 45,
				type: 'single',
			},
			{
				id: '6',
				label: '6',
				channel: 0,
				number: 1,
				velocity: 46,
				type: 'single',
			},
			{
				id: '7',
				label: '7',
				channel: 0,
				number: 1,
				velocity: 47,
				type: 'single',
			},
		],
	},
	{
		id: 'Activation__Wash Band',
		label: 'Activation - Wash Band',
		isLogical: false,
		type: 'indexed',
		enum: null,
		class: 'physical',
		values: [
			{
				id: 'Always on',
				label: 'Always on',
				channel: 0,
				number: 1,
				velocity: 25,
				type: 'single',
			},
			{
				id: 'Bass',
				label: 'Bass',
				channel: 0,
				number: 1,
				velocity: 26,
				type: 'single',
			},
			{
				id: 'Low Mid',
				label: 'Low Mid',
				channel: 0,
				number: 1,
				velocity: 27,
				type: 'single',
			},
			{
				id: 'Upper Mid',
				label: 'Upper Mid',
				channel: 0,
				number: 1,
				velocity: 28,
				type: 'single',
			},
			{
				id: 'Treble',
				label: 'Treble',
				channel: 0,
				number: 1,
				velocity: 29,
				type: 'single',
			},
		],
	},
	{
		id: 'Activation__Spot Band',
		label: 'Activation - Spot Band',
		isLogical: false,
		type: 'indexed',
		enum: null,
		class: 'physical',
		values: [
			{
				id: 'Always on',
				label: 'Always on',
				channel: 0,
				number: 1,
				velocity: 30,
				type: 'single',
			},
			{
				id: 'Bass',
				label: 'Bass',
				channel: 0,
				number: 1,
				velocity: 31,
				type: 'single',
			},
			{
				id: 'Low Mid',
				label: 'Low Mid',
				channel: 0,
				number: 1,
				velocity: 32,
				type: 'single',
			},
			{
				id: 'Upper Mid',
				label: 'Upper Mid',
				channel: 0,
				number: 1,
				velocity: 33,
				type: 'single',
			},
			{
				id: 'Treble',
				label: 'Treble',
				channel: 0,
				number: 1,
				velocity: 34,
				type: 'single',
			},
		],
	},
	{
		id: 'Activation__Laser Band',
		label: 'Activation - Laser Band',
		isLogical: false,
		type: 'indexed',
		enum: null,
		class: 'physical',
		values: [
			{
				id: 'Always on',
				label: 'Always on',
				channel: 0,
				number: 1,
				velocity: 35,
				type: 'single',
			},
			{
				id: 'Bass',
				label: 'Bass',
				channel: 0,
				number: 1,
				velocity: 36,
				type: 'single',
			},
			{
				id: 'Low Mid',
				label: 'Low Mid',
				channel: 0,
				number: 1,
				velocity: 37,
				type: 'single',
			},
			{
				id: 'Upper Mid',
				label: 'Upper Mid',
				channel: 0,
				number: 1,
				velocity: 38,
				type: 'single',
			},
			{
				id: 'Treble',
				label: 'Treble',
				channel: 0,
				number: 1,
				velocity: 39,
				type: 'single',
			},
		],
	},
]

export default buttons

export const maxLogicalIndex = Math.max(
	...buttons.filter((option) => option.type === 'indexed').map((option) => option.values.length - 1),
)
