import type MappingData from './mapping_data.js'

export const buttons: MappingData[] = [
	{
		id: 'Macro__Apply',
		label: 'Macro - Apply',
		channel: 0,
		number: 0,
		velocity: 42,
		enum: '',
	},
	{
		id: 'Macro__Clear Apply',
		label: 'Macro - Clear Apply',
		channel: 0,
		number: 0,
		velocity: 43,
		enum: '',
	},
	{
		id: 'Macro__Macro 0',
		label: 'Macro - Macro 0',
		channel: 0,
		number: 0,
		velocity: 47,
		enum: '',
	},
	{
		id: 'Macro__Macro 1',
		label: 'Macro - Macro 1',
		channel: 0,
		number: 0,
		velocity: 48,
		enum: '',
	},
	{
		id: 'Macro__Macro 2',
		label: 'Macro - Macro 2',
		channel: 0,
		number: 0,
		velocity: 49,
		enum: '',
	},
	{
		id: 'Macro__Macro 3',
		label: 'Macro - Macro 3',
		channel: 0,
		number: 0,
		velocity: 50,
		enum: '',
	},
	{
		id: 'Macro__Macro 4',
		label: 'Macro - Macro 4',
		channel: 0,
		number: 0,
		velocity: 51,
		enum: '',
	},
	{
		id: 'Macro__Macro 5',
		label: 'Macro - Macro 5',
		channel: 0,
		number: 0,
		velocity: 52,
		enum: '',
	},
	{
		id: 'Macro__Macro 6',
		label: 'Macro - Macro 6',
		channel: 0,
		number: 0,
		velocity: 53,
		enum: '',
	},
	{
		id: 'Macro__Macro 7',
		label: 'Macro - Macro 7',
		channel: 0,
		number: 0,
		velocity: 54,
		enum: '',
	},
	{
		id: 'Macro__Macro 8',
		label: 'Macro - Macro 8',
		channel: 0,
		number: 0,
		velocity: 55,
		enum: '',
	},
	{
		id: 'Macro__Macro 9',
		label: 'Macro - Macro 9',
		channel: 0,
		number: 0,
		velocity: 56,
		enum: '',
	},
	{
		id: 'Macro__Macro 10',
		label: 'Macro - Macro 10',
		channel: 0,
		number: 0,
		velocity: 57,
		enum: '',
	},
	{
		id: 'Macro__Macro 11',
		label: 'Macro - Macro 11',
		channel: 0,
		number: 0,
		velocity: 58,
		enum: '',
	},
	{
		id: 'Macro__Macro 12',
		label: 'Macro - Macro 12',
		channel: 0,
		number: 0,
		velocity: 59,
		enum: '',
	},
	{
		id: 'Macro__Macro 13',
		label: 'Macro - Macro 13',
		channel: 0,
		number: 0,
		velocity: 60,
		enum: '',
	},
	{
		id: 'Macro__Macro 14',
		label: 'Macro - Macro 14',
		channel: 0,
		number: 0,
		velocity: 61,
		enum: '',
	},
	{
		id: 'Macro__Macro 15',
		label: 'Macro - Macro 15',
		channel: 0,
		number: 0,
		velocity: 62,
		enum: '',
	},
	{
		id: 'Macro__Macro 16',
		label: 'Macro - Macro 16',
		channel: 0,
		number: 0,
		velocity: 63,
		enum: '',
	},
	{
		id: 'Macro__Macro 17',
		label: 'Macro - Macro 17',
		channel: 0,
		number: 0,
		velocity: 64,
		enum: '',
	},
	{
		id: 'Macro__Macro 18',
		label: 'Macro - Macro 18',
		channel: 0,
		number: 0,
		velocity: 65,
		enum: '',
	},
	{
		id: 'Macro__Macro 19',
		label: 'Macro - Macro 19',
		channel: 0,
		number: 0,
		velocity: 66,
		enum: '',
	},
	{
		id: 'Macro__Macro 20',
		label: 'Macro - Macro 20',
		channel: 0,
		number: 0,
		velocity: 67,
		enum: '',
	},
	{
		id: 'Macro__Macro 21',
		label: 'Macro - Macro 21',
		channel: 0,
		number: 0,
		velocity: 68,
		enum: '',
	},
	{
		id: 'Macro__Macro 22',
		label: 'Macro - Macro 22',
		channel: 0,
		number: 0,
		velocity: 69,
		enum: '',
	},
	{
		id: 'Macro__Macro 23',
		label: 'Macro - Macro 23',
		channel: 0,
		number: 0,
		velocity: 70,
		enum: '',
	},
	{
		id: 'Macro__Macro 24',
		label: 'Macro - Macro 24',
		channel: 0,
		number: 0,
		velocity: 71,
		enum: '',
	},
	{
		id: 'Macro__Macro 25',
		label: 'Macro - Macro 25',
		channel: 0,
		number: 0,
		velocity: 72,
		enum: '',
	},
	{
		id: 'Macro__Macro 26',
		label: 'Macro - Macro 26',
		channel: 0,
		number: 0,
		velocity: 73,
		enum: '',
	},
	{
		id: 'Macro__Macro 27',
		label: 'Macro - Macro 27',
		channel: 0,
		number: 0,
		velocity: 74,
		enum: '',
	},
	{
		id: 'Macro__Macro 28',
		label: 'Macro - Macro 28',
		channel: 0,
		number: 0,
		velocity: 75,
		enum: '',
	},
	{
		id: 'Macro__Macro 29',
		label: 'Macro - Macro 29',
		channel: 0,
		number: 0,
		velocity: 76,
		enum: '',
	},
	{
		id: 'Macro__Macro 30',
		label: 'Macro - Macro 30',
		channel: 0,
		number: 0,
		velocity: 77,
		enum: '',
	},
	{
		id: 'Macro__Macro 31',
		label: 'Macro - Macro 31',
		channel: 0,
		number: 0,
		velocity: 78,
		enum: '',
	},
	{
		id: 'Effect__Confetti',
		label: 'Effect - Confetti',
		channel: 0,
		number: 0,
		velocity: 79,
		enum: '',
	},
	{
		id: 'Effect__Co2 Down',
		label: 'Effect - Co2 Down',
		channel: 0,
		number: 0,
		velocity: 80,
		enum: '',
	},
	{
		id: 'Effect__Co2 Up',
		label: 'Effect - Co2 Up',
		channel: 0,
		number: 0,
		velocity: 81,
		enum: '',
	},
	{
		id: 'Effect__Fire',
		label: 'Effect - Fire',
		channel: 0,
		number: 0,
		velocity: 82,
		enum: '',
	},
	{
		id: 'Effect__Bubbles',
		label: 'Effect - Bubbles',
		channel: 0,
		number: 0,
		velocity: 83,
		enum: '',
	},
	{
		id: 'Effect__Reset',
		label: 'Effect - Reset',
		channel: 0,
		number: 0,
		velocity: 84,
		enum: '',
	},
	{
		id: 'Activation__Section Enabled',
		label: 'Activation - Section Enabled',
		channel: 0,
		number: 1,
		velocity: 0,
		enum: '',
	},
	{
		id: 'Activation__Spot Enabled',
		label: 'Activation - Spot Enabled',
		channel: 0,
		number: 1,
		velocity: 1,
		enum: '',
	},
	{
		id: 'Activation__Wash Enabled',
		label: 'Activation - Wash Enabled',
		channel: 0,
		number: 1,
		velocity: 2,
		enum: '',
	},
	{
		id: 'Effect__Laser Enabled',
		label: 'Effect - Laser Enabled',
		channel: 0,
		number: 1,
		velocity: 3,
		enum: '',
	},
	{
		id: 'General__Color 0',
		label: 'General - Color 0',
		channel: 0,
		number: 1,
		velocity: 4,
		enum: '',
	},
	{
		id: 'General__Color 1',
		label: 'General - Color 1',
		channel: 0,
		number: 1,
		velocity: 5,
		enum: '',
	},
	{
		id: 'General__Color 2',
		label: 'General - Color 2',
		channel: 0,
		number: 1,
		velocity: 6,
		enum: '',
	},
	{
		id: 'General__Color 3',
		label: 'General - Color 3',
		channel: 0,
		number: 1,
		velocity: 7,
		enum: '',
	},
	{
		id: 'General__Color 4',
		label: 'General - Color 4',
		channel: 0,
		number: 1,
		velocity: 8,
		enum: '',
	},
	{
		id: 'General__Color 5',
		label: 'General - Color 5',
		channel: 0,
		number: 1,
		velocity: 9,
		enum: '',
	},
	{
		id: 'General__Color 6',
		label: 'General - Color 6',
		channel: 0,
		number: 1,
		velocity: 10,
		enum: '',
	},
	{
		id: 'General__Color 7',
		label: 'General - Color 7',
		channel: 0,
		number: 1,
		velocity: 11,
		enum: '',
	},
	{
		id: 'General__Color 8',
		label: 'General - Color 8',
		channel: 0,
		number: 1,
		velocity: 12,
		enum: '',
	},
	{
		id: 'General__Color 9',
		label: 'General - Color 9',
		channel: 0,
		number: 1,
		velocity: 13,
		enum: '',
	},
	{
		id: 'General__Color 10',
		label: 'General - Color 10',
		channel: 0,
		number: 1,
		velocity: 14,
		enum: '',
	},
	{
		id: 'General__Color 11',
		label: 'General - Color 11',
		channel: 0,
		number: 1,
		velocity: 15,
		enum: '',
	},
	{
		id: 'General__Color 12',
		label: 'General - Color 12',
		channel: 0,
		number: 1,
		velocity: 16,
		enum: '',
	},
	{
		id: 'General__Color 13',
		label: 'General - Color 13',
		channel: 0,
		number: 1,
		velocity: 17,
		enum: '',
	},
	{
		id: 'General__Color 14',
		label: 'General - Color 14',
		channel: 0,
		number: 1,
		velocity: 18,
		enum: '',
	},
	{
		id: 'General__Color 15',
		label: 'General - Color 15',
		channel: 0,
		number: 1,
		velocity: 19,
		enum: '',
	},
	{
		id: 'Midi Only__Write `[Neoluma][Midi] Pong` to Log, if Ready',
		label: 'Midi Only - Write `[Neoluma][Midi] Pong` to Log, if Ready',
		channel: 0,
		number: 1,
		velocity: 20,
		enum: '',
	},
	{
		id: 'Activation__Wash Band: Always on',
		label: 'Activation - Wash Band: Always on',
		channel: 0,
		number: 1,
		velocity: 25,
		enum: '',
	},
	{
		id: 'Activation__Wash Band: Bass',
		label: 'Activation - Wash Band: Bass',
		channel: 0,
		number: 1,
		velocity: 26,
		enum: '',
	},
	{
		id: 'Activation__Wash Band: Low Mid',
		label: 'Activation - Wash Band: Low Mid',
		channel: 0,
		number: 1,
		velocity: 27,
		enum: '',
	},
	{
		id: 'Activation__Wash Band: Upper Mid',
		label: 'Activation - Wash Band: Upper Mid',
		channel: 0,
		number: 1,
		velocity: 28,
		enum: '',
	},
	{
		id: 'Activation__Wash Band: Treble',
		label: 'Activation - Wash Band: Treble',
		channel: 0,
		number: 1,
		velocity: 29,
		enum: '',
	},
	{
		id: 'Activation__Spot Band: Always on',
		label: 'Activation - Spot Band: Always on',
		channel: 0,
		number: 1,
		velocity: 30,
		enum: '',
	},
	{
		id: 'Activation__Spot Band: Bass',
		label: 'Activation - Spot Band: Bass',
		channel: 0,
		number: 1,
		velocity: 31,
		enum: '',
	},
	{
		id: 'Activation__Spot Band: Low Mid',
		label: 'Activation - Spot Band: Low Mid',
		channel: 0,
		number: 1,
		velocity: 32,
		enum: '',
	},
	{
		id: 'Activation__Spot Band: Upper Mid',
		label: 'Activation - Spot Band: Upper Mid',
		channel: 0,
		number: 1,
		velocity: 33,
		enum: '',
	},
	{
		id: 'Activation__Spot Band: Treble',
		label: 'Activation - Spot Band: Treble',
		channel: 0,
		number: 1,
		velocity: 34,
		enum: '',
	},
	{
		id: 'Activation__Laser Band: Always on',
		label: 'Activation - Laser Band: Always on',
		channel: 0,
		number: 1,
		velocity: 35,
		enum: '',
	},
	{
		id: 'Activation__Laser Band: Bass',
		label: 'Activation - Laser Band: Bass',
		channel: 0,
		number: 1,
		velocity: 36,
		enum: '',
	},
	{
		id: 'Activation__Laser Band: Low Mid',
		label: 'Activation - Laser Band: Low Mid',
		channel: 0,
		number: 1,
		velocity: 37,
		enum: '',
	},
	{
		id: 'Activation__Laser Band: Upper Mid',
		label: 'Activation - Laser Band: Upper Mid',
		channel: 0,
		number: 1,
		velocity: 38,
		enum: '',
	},
	{
		id: 'Activation__Laser Band: Treble',
		label: 'Activation - Laser Band: Treble',
		channel: 0,
		number: 1,
		velocity: 39,
		enum: '',
	},
	{
		id: 'General__Gobo: 0',
		label: 'General - Gobo: 0',
		channel: 0,
		number: 1,
		velocity: 40,
		enum: '',
	},
	{
		id: 'General__Gobo: 1',
		label: 'General - Gobo: 1',
		channel: 0,
		number: 1,
		velocity: 41,
		enum: '',
	},
	{
		id: 'General__Gobo: 2',
		label: 'General - Gobo: 2',
		channel: 0,
		number: 1,
		velocity: 42,
		enum: '',
	},
	{
		id: 'General__Gobo: 3',
		label: 'General - Gobo: 3',
		channel: 0,
		number: 1,
		velocity: 43,
		enum: '',
	},
	{
		id: 'General__Gobo: 4',
		label: 'General - Gobo: 4',
		channel: 0,
		number: 1,
		velocity: 44,
		enum: '',
	},
	{
		id: 'General__Gobo: 5',
		label: 'General - Gobo: 5',
		channel: 0,
		number: 1,
		velocity: 45,
		enum: '',
	},
	{
		id: 'General__Gobo: 6',
		label: 'General - Gobo: 6',
		channel: 0,
		number: 1,
		velocity: 46,
		enum: '',
	},
	{
		id: 'General__Gobo: 7',
		label: 'General - Gobo: 7',
		channel: 0,
		number: 1,
		velocity: 47,
		enum: '',
	},
	{
		id: 'General__Gobo Spin Speed Reverse',
		label: 'General - Gobo Spin Speed Reverse',
		channel: 0,
		number: 1,
		velocity: 48,
		enum: '',
	},
	{
		id: 'Advanced__Force Resync All',
		label: 'Advanced - Force Resync All',
		channel: 0,
		number: 1,
		velocity: 57,
		enum: '',
	},
	{
		id: 'AudioLink__Reset Settings',
		label: 'AudioLink - Reset Settings',
		channel: 0,
		number: 1,
		velocity: 115,
		enum: '',
	},
	{
		id: 'AudioLink Smoothing__Reset Settings',
		label: 'AudioLink Smoothing - Reset Settings',
		channel: 0,
		number: 1,
		velocity: 116,
		enum: '',
	},
	{
		id: 'General__UI Larger',
		label: 'General - UI Larger',
		channel: 0,
		number: 1,
		velocity: 117,
		enum: '',
	},
	{
		id: 'General__UI Smaller',
		label: 'General - UI Smaller',
		channel: 0,
		number: 1,
		velocity: 118,
		enum: '',
	},
	{
		id: 'Midi Only__Dump All State as Feedback',
		label: 'Midi Only - Dump All State as Feedback',
		channel: 0,
		number: 1,
		velocity: 121,
		enum: '',
	},

	// Logical
	{
		id: 'Macro__Use Macro 0-31',
		label: 'Macro - Use Macro 0-31',
		channel: 0,
		number: 37,
		velocity: 0,
		enum: '',
		isLogical: 31 - 0 + 1,
	},
	{
		id: 'Macro__Set Macro 0-31',
		label: 'Macro - Set Macro 0-31',
		channel: 0,
		number: 37,
		velocity: 32,
		enum: '',
		isLogical: 63 - 32 + 1,
	},
	{
		id: 'General__Set Color 0-15',
		label: 'General - Set Color 0-15',
		channel: 0,
		number: 56,
		velocity: 64,
		enum: '',
		isLogical: 79 - 64 + 1,
	},
]

export default buttons

export const maxLogicalIndex = Math.max(
	...buttons.map((option) => option.isLogical).filter((option) => typeof option === 'number'),
)
