import type MappingData from './mapping_data.js'

export const enums: MappingData[] = [
	{
		id: 'Wall Line Activation__Wall Lines: Fix',
		label: 'Wall Line Activation - Wall Lines: Fix',
		channel: 0,
		number: 1,
		velocity: 49,
		enum: 'WallLines',
	},
	{
		id: 'Wall Line Activation__Wall Lines: Audio Link',
		label: 'Wall Line Activation - Wall Lines: Audio Link',
		channel: 0,
		number: 1,
		velocity: 50,
		enum: 'WallLines',
	},
	{
		id: 'Wall Line Activation__Wall Lines: Wave Forward',
		label: 'Wall Line Activation - Wall Lines: Wave Forward',
		channel: 0,
		number: 1,
		velocity: 51,
		enum: 'WallLines',
	},
	{
		id: 'Wall Line Activation__Wall Lines: Wave Center',
		label: 'Wall Line Activation - Wall Lines: Wave Center',
		channel: 0,
		number: 1,
		velocity: 52,
		enum: 'WallLines',
	},
	{
		id: 'Wall Line Activation__Wall Lines: Wave Up',
		label: 'Wall Line Activation - Wall Lines: Wave Up',
		channel: 0,
		number: 1,
		velocity: 53,
		enum: 'WallLines',
	},
	{
		id: 'Wall Line Activation__Wall Lines: Wave Down',
		label: 'Wall Line Activation - Wall Lines: Wave Down',
		channel: 0,
		number: 1,
		velocity: 54,
		enum: 'WallLines',
	},
	{
		id: 'Wall Line Activation__Wall Lines: Flash',
		label: 'Wall Line Activation - Wall Lines: Flash',
		channel: 0,
		number: 1,
		velocity: 55,
		enum: 'WallLines',
	},
	{
		id: 'Wall Line Activation__Wall Lines: RESERVED',
		label: 'Wall Line Activation - Wall Lines: RESERVED',
		channel: 0,
		number: 1,
		velocity: 56,
		enum: 'WallLines',
	},
	{
		id: 'Movement__Spot Movement: Static',
		label: 'Movement - Spot Movement: Static',
		channel: 0,
		number: 1,
		velocity: 66,
		enum: 'SpotMovement',
	},
	{
		id: 'Movement__Spot Movement: Wave Forward',
		label: 'Movement - Spot Movement: Wave Forward',
		channel: 0,
		number: 1,
		velocity: 67,
		enum: 'SpotMovement',
	},
	{
		id: 'Movement__Spot Movement: Wave Backward',
		label: 'Movement - Spot Movement: Wave Backward',
		channel: 0,
		number: 1,
		velocity: 68,
		enum: 'SpotMovement',
	},
	{
		id: 'Movement__Spot Movement: Circle Backward',
		label: 'Movement - Spot Movement: Circle Backward',
		channel: 0,
		number: 1,
		velocity: 69,
		enum: 'SpotMovement',
	},
	{
		id: 'Movement__Spot Movement: Circle Forward',
		label: 'Movement - Spot Movement: Circle Forward',
		channel: 0,
		number: 1,
		velocity: 70,
		enum: 'SpotMovement',
	},
	{
		id: 'Movement__Spot Movement: Random',
		label: 'Movement - Spot Movement: Random',
		channel: 0,
		number: 1,
		velocity: 71,
		enum: 'SpotMovement',
	},
	{
		id: 'Movement__Spot Movement: Strike',
		label: 'Movement - Spot Movement: Strike',
		channel: 0,
		number: 1,
		velocity: 72,
		enum: 'SpotMovement',
	},
	{
		id: 'Movement__Spot Movement: RESERVED',
		label: 'Movement - Spot Movement: RESERVED',
		channel: 0,
		number: 1,
		velocity: 73,
		enum: 'SpotMovement',
	},
	{
		id: 'Movement__Wash Movement: Static',
		label: 'Movement - Wash Movement: Static',
		channel: 0,
		number: 1,
		velocity: 74,
		enum: 'WashMovement',
	},
	{
		id: 'Movement__Wash Movement: Wash',
		label: 'Movement - Wash Movement: Wash',
		channel: 0,
		number: 1,
		velocity: 75,
		enum: 'WashMovement',
	},
	{
		id: 'Movement__Wash Movement: Strike',
		label: 'Movement - Wash Movement: Strike',
		channel: 0,
		number: 1,
		velocity: 76,
		enum: 'WashMovement',
	},
	{
		id: 'Movement__Wash Movement: RESERVED',
		label: 'Movement - Wash Movement: RESERVED',
		channel: 0,
		number: 1,
		velocity: 77,
		enum: 'WashMovement',
	},
	{
		id: 'General__Random: Off',
		label: 'General - Random: Off',
		channel: 0,
		number: 1,
		velocity: 78,
		enum: 'Random',
	},
	{
		id: 'General__Random: Wave',
		label: 'General - Random: Wave',
		channel: 0,
		number: 1,
		velocity: 79,
		enum: 'Random',
	},
	{
		id: 'General__Random: Random',
		label: 'General - Random: Random',
		channel: 0,
		number: 1,
		velocity: 80,
		enum: 'Random',
	},
	{
		id: 'General__Random: All',
		label: 'General - Random: All',
		channel: 0,
		number: 1,
		velocity: 81,
		enum: 'Random',
	},
	{
		id: 'Effect__Flasher: Off',
		label: 'Effect - Flasher: Off',
		channel: 0,
		number: 1,
		velocity: 83,
		enum: 'Flasher',
	},
	{
		id: 'Effect__Flasher: Audio Link',
		label: 'Effect - Flasher: Audio Link',
		channel: 0,
		number: 1,
		velocity: 84,
		enum: 'Flasher',
	},
	{
		id: 'Effect__Flasher: Random Audio Link',
		label: 'Effect - Flasher: Random Audio Link',
		channel: 0,
		number: 1,
		velocity: 85,
		enum: 'Flasher',
	},
	{
		id: 'Effect__Flasher: Hard Audio Link',
		label: 'Effect - Flasher: Hard Audio Link',
		channel: 0,
		number: 1,
		velocity: 86,
		enum: 'Flasher',
	},
	{
		id: 'Effect__Flasher: Random',
		label: 'Effect - Flasher: Random',
		channel: 0,
		number: 1,
		velocity: 87,
		enum: 'Flasher',
	},
	{
		id: 'Effect__Flasher: Hard',
		label: 'Effect - Flasher: Hard',
		channel: 0,
		number: 1,
		velocity: 88,
		enum: 'Flasher',
	},
	{
		id: 'Effect__Flasher: RESERVED',
		label: 'Effect - Flasher: RESERVED',
		channel: 0,
		number: 1,
		velocity: 89,
		enum: 'Flasher',
	},
	{
		id: 'Effect__Flasher: RESERVED',
		label: 'Effect - Flasher: RESERVED',
		channel: 0,
		number: 1,
		velocity: 90,
		enum: 'Flasher',
	},
	{
		id: 'Effect__Moving Head Strobe: Off',
		label: 'Effect - Moving Head Strobe: Off',
		channel: 0,
		number: 1,
		velocity: 91,
		enum: 'MovingHeadStrobe',
	},
	{
		id: 'Effect__Moving Head Strobe: Random',
		label: 'Effect - Moving Head Strobe: Random',
		channel: 0,
		number: 1,
		velocity: 92,
		enum: 'MovingHeadStrobe',
	},
	{
		id: 'Effect__Moving Head Strobe: Section Random',
		label: 'Effect - Moving Head Strobe: Section Random',
		channel: 0,
		number: 1,
		velocity: 93,
		enum: 'MovingHeadStrobe',
	},
	{
		id: 'Effect__Moving Head Strobe: Hard',
		label: 'Effect - Moving Head Strobe: Hard',
		channel: 0,
		number: 1,
		velocity: 94,
		enum: 'MovingHeadStrobe',
	},
	{
		id: 'Advanced__Screen Mapping: Full',
		label: 'Advanced - Screen Mapping: Full',
		channel: 0,
		number: 1,
		velocity: 95,
		enum: 'ScreenMapping',
	},
	{
		id: 'Advanced__Screen Mapping: Cropped DMX',
		label: 'Advanced - Screen Mapping: Cropped DMX',
		channel: 0,
		number: 1,
		velocity: 96,
		enum: 'ScreenMapping',
	},
	{
		id: 'Advanced__Screen Mapping: Mapped',
		label: 'Advanced - Screen Mapping: Mapped',
		channel: 0,
		number: 1,
		velocity: 97,
		enum: 'ScreenMapping',
	},
	{
		id: 'Advanced__Screen Mapping: RESERVED',
		label: 'Advanced - Screen Mapping: RESERVED',
		channel: 0,
		number: 1,
		velocity: 98,
		enum: 'ScreenMapping',
	},
	{
		id: 'Wall Line Colors__Initialize',
		label: 'Wall Line Colors - Initialize',
		channel: 0,
		number: 1,
		velocity: 99,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Deepsea',
		label: 'Wall Line Colors - Deepsea',
		channel: 0,
		number: 1,
		velocity: 100,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Skyhigh',
		label: 'Wall Line Colors - Skyhigh',
		channel: 0,
		number: 1,
		velocity: 101,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Lavender',
		label: 'Wall Line Colors - Lavender',
		channel: 0,
		number: 1,
		velocity: 102,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Lovepotion',
		label: 'Wall Line Colors - Lovepotion',
		channel: 0,
		number: 1,
		velocity: 103,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Yumekawa',
		label: 'Wall Line Colors - Yumekawa',
		channel: 0,
		number: 1,
		velocity: 104,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Sunset',
		label: 'Wall Line Colors - Sunset',
		channel: 0,
		number: 1,
		velocity: 105,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Goldenage',
		label: 'Wall Line Colors - Goldenage',
		channel: 0,
		number: 1,
		velocity: 106,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Redlight',
		label: 'Wall Line Colors - Redlight',
		channel: 0,
		number: 1,
		velocity: 107,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Takefive',
		label: 'Wall Line Colors - Takefive',
		channel: 0,
		number: 1,
		velocity: 108,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Garden',
		label: 'Wall Line Colors - Garden',
		channel: 0,
		number: 1,
		velocity: 109,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Energize',
		label: 'Wall Line Colors - Energize',
		channel: 0,
		number: 1,
		velocity: 110,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Happy',
		label: 'Wall Line Colors - Happy',
		channel: 0,
		number: 1,
		velocity: 111,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Poppinshower',
		label: 'Wall Line Colors - Poppinshower',
		channel: 0,
		number: 1,
		velocity: 112,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__RGB',
		label: 'Wall Line Colors - RGB',
		channel: 0,
		number: 1,
		velocity: 113,
		enum: 'WallLineColors',
	},
	{
		id: 'Wall Line Colors__Turquise',
		label: 'Wall Line Colors - Turquise',
		channel: 0,
		number: 1,
		velocity: 114,
		enum: 'WallLineColors',
	},

	// Logical
	{
		id: 'Activation__Wash Band: Always on',
		label: 'Activation - Wash Band: Always on',
		channel: 0,
		number: 38,
		velocity: 64,
		enum: 'WashBand',
		isLogical: true,
	},
	{
		id: 'Activation__Wash Band: Bass',
		label: 'Activation - Wash Band: Bass',
		channel: 0,
		number: 38,
		velocity: 96,
		enum: 'WashBand',
		isLogical: true,
	},
	{
		id: 'Activation__Wash Band: Low Mid',
		label: 'Activation - Wash Band: Low Mid',
		channel: 0,
		number: 39,
		velocity: 0,
		enum: 'WashBand',
		isLogical: true,
	},
	{
		id: 'Activation__Wash Band: Upper Mid',
		label: 'Activation - Wash Band: Upper Mid',
		channel: 0,
		number: 39,
		velocity: 32,
		enum: 'WashBand',
		isLogical: true,
	},
	{
		id: 'Activation__Wash Band: Treble',
		label: 'Activation - Wash Band: Treble',
		channel: 0,
		number: 39,
		velocity: 64,
		enum: 'WashBand',
		isLogical: true,
	},
	{
		id: 'Activation__Spot Band: Always on',
		label: 'Activation - Spot Band: Always on',
		channel: 0,
		number: 39,
		velocity: 96,
		enum: 'SpotBand',
		isLogical: true,
	},
	{
		id: 'Activation__Spot Band: Bass',
		label: 'Activation - Spot Band: Bass',
		channel: 0,
		number: 40,
		velocity: 0,
		enum: 'SpotBand',
		isLogical: true,
	},
	{
		id: 'Activation__Spot Band: Low Mid',
		label: 'Activation - Spot Band: Low Mid',
		channel: 0,
		number: 40,
		velocity: 32,
		enum: 'SpotBand',
		isLogical: true,
	},
	{
		id: 'Activation__Spot Band: Upper Mid',
		label: 'Activation - Spot Band: Upper Mid',
		channel: 0,
		number: 40,
		velocity: 64,
		enum: 'SpotBand',
		isLogical: true,
	},
	{
		id: 'Activation__Spot Band: Treble',
		label: 'Activation - Spot Band: Treble',
		channel: 0,
		number: 40,
		velocity: 96,
		enum: 'SpotBand',
		isLogical: true,
	},
	{
		id: 'Activation__Laser Band: Always on',
		label: 'Activation - Laser Band: Always on',
		channel: 0,
		number: 41,
		velocity: 0,
		enum: 'LaserBand',
		isLogical: true,
	},
	{
		id: 'Activation__Laser Band: Bass',
		label: 'Activation - Laser Band: Bass',
		channel: 0,
		number: 41,
		velocity: 32,
		enum: 'LaserBand',
		isLogical: true,
	},
	{
		id: 'Activation__Laser Band: Low Mid',
		label: 'Activation - Laser Band: Low Mid',
		channel: 0,
		number: 41,
		velocity: 64,
		enum: 'LaserBand',
		isLogical: true,
	},
	{
		id: 'Activation__Laser Band: Upper Mid',
		label: 'Activation - Laser Band: Upper Mid',
		channel: 0,
		number: 41,
		velocity: 96,
		enum: 'LaserBand',
		isLogical: true,
	},
	{
		id: 'Activation__Laser Band: Treble',
		label: 'Activation - Laser Band: Treble',
		channel: 0,
		number: 42,
		velocity: 0,
		enum: 'LaserBand',
		isLogical: true,
	},
	{
		id: 'General__Gobo: 0',
		label: 'General - Gobo: 0',
		channel: 0,
		number: 42,
		velocity: 32,
		enum: 'Gobo',
		isLogical: true,
	},
	{
		id: 'General__Gobo: 1',
		label: 'General - Gobo: 1',
		channel: 0,
		number: 42,
		velocity: 64,
		enum: 'Gobo',
		isLogical: true,
	},
	{
		id: 'General__Gobo: 2',
		label: 'General - Gobo: 2',
		channel: 0,
		number: 42,
		velocity: 96,
		enum: 'Gobo',
		isLogical: true,
	},
	{
		id: 'General__Gobo: 3',
		label: 'General - Gobo: 3',
		channel: 0,
		number: 43,
		velocity: 0,
		enum: 'Gobo',
		isLogical: true,
	},
	{
		id: 'General__Gobo: 4',
		label: 'General - Gobo: 4',
		channel: 0,
		number: 43,
		velocity: 32,
		enum: 'Gobo',
		isLogical: true,
	},
	{
		id: 'General__Gobo: 5',
		label: 'General - Gobo: 5',
		channel: 0,
		number: 43,
		velocity: 64,
		enum: 'Gobo',
		isLogical: true,
	},
	{
		id: 'General__Gobo: 6',
		label: 'General - Gobo: 6',
		channel: 0,
		number: 43,
		velocity: 96,
		enum: 'Gobo',
		isLogical: true,
	},
	{
		id: 'General__Gobo: 7',
		label: 'General - Gobo: 7',
		channel: 0,
		number: 44,
		velocity: 0,
		enum: 'Gobo',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 0',
		label: 'General - Set Spot to Color: 0',
		channel: 0,
		number: 44,
		velocity: 64,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 1',
		label: 'General - Set Spot to Color: 1',
		channel: 0,
		number: 44,
		velocity: 96,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 2',
		label: 'General - Set Spot to Color: 2',
		channel: 0,
		number: 45,
		velocity: 0,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 3',
		label: 'General - Set Spot to Color: 3',
		channel: 0,
		number: 45,
		velocity: 32,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 4',
		label: 'General - Set Spot to Color: 4',
		channel: 0,
		number: 45,
		velocity: 64,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 5',
		label: 'General - Set Spot to Color: 5',
		channel: 0,
		number: 45,
		velocity: 96,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 6',
		label: 'General - Set Spot to Color: 6',
		channel: 0,
		number: 46,
		velocity: 0,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 7',
		label: 'General - Set Spot to Color: 7',
		channel: 0,
		number: 46,
		velocity: 32,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 8',
		label: 'General - Set Spot to Color: 8',
		channel: 0,
		number: 46,
		velocity: 64,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 9',
		label: 'General - Set Spot to Color: 9',
		channel: 0,
		number: 46,
		velocity: 96,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 10',
		label: 'General - Set Spot to Color: 10',
		channel: 0,
		number: 47,
		velocity: 0,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 11',
		label: 'General - Set Spot to Color: 11',
		channel: 0,
		number: 47,
		velocity: 32,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 12',
		label: 'General - Set Spot to Color: 12',
		channel: 0,
		number: 47,
		velocity: 64,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 13',
		label: 'General - Set Spot to Color: 13',
		channel: 0,
		number: 47,
		velocity: 96,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 14',
		label: 'General - Set Spot to Color: 14',
		channel: 0,
		number: 48,
		velocity: 0,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Spot to Color: 15',
		label: 'General - Set Spot to Color: 15',
		channel: 0,
		number: 48,
		velocity: 32,
		enum: 'SpotColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 0',
		label: 'General - Set Wash to Color: 0',
		channel: 0,
		number: 48,
		velocity: 64,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 1',
		label: 'General - Set Wash to Color: 1',
		channel: 0,
		number: 48,
		velocity: 96,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 2',
		label: 'General - Set Wash to Color: 2',
		channel: 0,
		number: 49,
		velocity: 0,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 3',
		label: 'General - Set Wash to Color: 3',
		channel: 0,
		number: 49,
		velocity: 32,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 4',
		label: 'General - Set Wash to Color: 4',
		channel: 0,
		number: 49,
		velocity: 64,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 5',
		label: 'General - Set Wash to Color: 5',
		channel: 0,
		number: 49,
		velocity: 96,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 6',
		label: 'General - Set Wash to Color: 6',
		channel: 0,
		number: 50,
		velocity: 0,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 7',
		label: 'General - Set Wash to Color: 7',
		channel: 0,
		number: 50,
		velocity: 32,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 8',
		label: 'General - Set Wash to Color: 8',
		channel: 0,
		number: 50,
		velocity: 64,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 9',
		label: 'General - Set Wash to Color: 9',
		channel: 0,
		number: 50,
		velocity: 96,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 10',
		label: 'General - Set Wash to Color: 10',
		channel: 0,
		number: 51,
		velocity: 0,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 11',
		label: 'General - Set Wash to Color: 11',
		channel: 0,
		number: 51,
		velocity: 32,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 12',
		label: 'General - Set Wash to Color: 12',
		channel: 0,
		number: 51,
		velocity: 64,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 13',
		label: 'General - Set Wash to Color: 13',
		channel: 0,
		number: 51,
		velocity: 96,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 14',
		label: 'General - Set Wash to Color: 14',
		channel: 0,
		number: 52,
		velocity: 0,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Wash to Color: 15',
		label: 'General - Set Wash to Color: 15',
		channel: 0,
		number: 52,
		velocity: 32,
		enum: 'WashColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 0',
		label: 'General - Set Laser to Color: 0',
		channel: 0,
		number: 52,
		velocity: 64,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 1',
		label: 'General - Set Laser to Color: 1',
		channel: 0,
		number: 52,
		velocity: 96,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 2',
		label: 'General - Set Laser to Color: 2',
		channel: 0,
		number: 53,
		velocity: 0,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 3',
		label: 'General - Set Laser to Color: 3',
		channel: 0,
		number: 53,
		velocity: 32,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 4',
		label: 'General - Set Laser to Color: 4',
		channel: 0,
		number: 53,
		velocity: 64,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 5',
		label: 'General - Set Laser to Color: 5',
		channel: 0,
		number: 53,
		velocity: 96,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 6',
		label: 'General - Set Laser to Color: 6',
		channel: 0,
		number: 54,
		velocity: 0,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 7',
		label: 'General - Set Laser to Color: 7',
		channel: 0,
		number: 54,
		velocity: 32,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 8',
		label: 'General - Set Laser to Color: 8',
		channel: 0,
		number: 54,
		velocity: 64,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 9',
		label: 'General - Set Laser to Color: 9',
		channel: 0,
		number: 54,
		velocity: 96,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 10',
		label: 'General - Set Laser to Color: 10',
		channel: 0,
		number: 55,
		velocity: 0,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 11',
		label: 'General - Set Laser to Color: 11',
		channel: 0,
		number: 55,
		velocity: 32,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 12',
		label: 'General - Set Laser to Color: 12',
		channel: 0,
		number: 55,
		velocity: 64,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 13',
		label: 'General - Set Laser to Color: 13',
		channel: 0,
		number: 55,
		velocity: 96,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 14',
		label: 'General - Set Laser to Color: 14',
		channel: 0,
		number: 56,
		velocity: 0,
		enum: 'LaserColor',
		isLogical: true,
	},
	{
		id: 'General__Set Laser to Color: 15',
		label: 'General - Set Laser to Color: 15',
		channel: 0,
		number: 56,
		velocity: 32,
		enum: 'LaserColor',
		isLogical: true,
	},
]

export default enums
