import type { MappingData } from './mapping_data.js'

export const enums: MappingData[] = [
	{
		id: 'Wall Line Activation__Wall Lines',
		label: 'Wall Line Activation - Wall Lines',
		isLogical: false,
		type: 'indexed',
		enum: 'WallLines',
		class: 'physical',
		values: [
			{
				id: 'Fix',
				label: 'Fix',
				channel: 0,
				number: 1,
				velocity: 49,
				type: 'single',
			},
			{
				id: 'Audio Link',
				label: 'Audio Link',
				channel: 0,
				number: 1,
				velocity: 50,
				type: 'single',
			},
			{
				id: 'Wave Forward',
				label: 'Wave Forward',
				channel: 0,
				number: 1,
				velocity: 51,
				type: 'single',
			},
			{
				id: 'Wave Center',
				label: 'Wave Center',
				channel: 0,
				number: 1,
				velocity: 52,
				type: 'single',
			},
			{
				id: 'Wave Up',
				label: 'Wave Up',
				channel: 0,
				number: 1,
				velocity: 53,
				type: 'single',
			},
			{
				id: 'Wave Down',
				label: 'Wave Down',
				channel: 0,
				number: 1,
				velocity: 54,
				type: 'single',
			},
			{
				id: 'Flash',
				label: 'Flash',
				channel: 0,
				number: 1,
				velocity: 55,
				type: 'single',
			},
			{
				id: 'RESERVED',
				label: 'RESERVED',
				channel: 0,
				number: 1,
				velocity: 56,
				type: 'single',
			},
		],
	},
	{
		id: 'Movement__Spot Movement',
		label: 'Movement - Spot Movement',
		isLogical: false,
		type: 'indexed',
		enum: 'SpotMovement',
		class: 'global',
		values: [
			{
				id: 'Static',
				label: 'Static',
				channel: 0,
				number: 1,
				velocity: 66,
				type: 'single',
			},
			{
				id: 'Wave Forward',
				label: 'Wave Forward',
				channel: 0,
				number: 1,
				velocity: 67,
				type: 'single',
			},
			{
				id: 'Wave Backward',
				label: 'Wave Backward',
				channel: 0,
				number: 1,
				velocity: 68,
				type: 'single',
			},
			{
				id: 'Circle Backward',
				label: 'Circle Backward',
				channel: 0,
				number: 1,
				velocity: 69,
				type: 'single',
			},
			{
				id: 'Circle Forward',
				label: 'Circle Forward',
				channel: 0,
				number: 1,
				velocity: 70,
				type: 'single',
			},
			{
				id: 'Random',
				label: 'Random',
				channel: 0,
				number: 1,
				velocity: 71,
				type: 'single',
			},
			{
				id: 'Strike',
				label: 'Strike',
				channel: 0,
				number: 1,
				velocity: 72,
				type: 'single',
			},
			{
				id: 'RESERVED',
				label: 'RESERVED',
				channel: 0,
				number: 1,
				velocity: 73,
				type: 'single',
			},
		],
	},
	{
		id: 'Movement__Wash Movement',
		label: 'Movement - Wash Movement',
		isLogical: false,
		type: 'indexed',
		enum: 'WashMovement',
		class: 'global',
		values: [
			{
				id: 'Static',
				label: 'Static',
				channel: 0,
				number: 1,
				velocity: 74,
				type: 'single',
			},
			{
				id: 'Wash',
				label: 'Wash',
				channel: 0,
				number: 1,
				velocity: 75,
				type: 'single',
			},
			{
				id: 'Strike',
				label: 'Strike',
				channel: 0,
				number: 1,
				velocity: 76,
				type: 'single',
			},
			{
				id: 'RESERVED',
				label: 'RESERVED',
				channel: 0,
				number: 1,
				velocity: 77,
				type: 'single',
			},
		],
	},
	{
		id: 'General__Random',
		label: 'General - Random',
		isLogical: false,
		type: 'indexed',
		enum: 'Random',
		class: 'global',
		values: [
			{
				id: 'Off',
				label: 'Off',
				channel: 0,
				number: 1,
				velocity: 78,
				type: 'single',
			},
			{
				id: 'Wave',
				label: 'Wave',
				channel: 0,
				number: 1,
				velocity: 79,
				type: 'single',
			},
			{
				id: 'Random',
				label: 'Random',
				channel: 0,
				number: 1,
				velocity: 80,
				type: 'single',
			},
			{
				id: 'All',
				label: 'All',
				channel: 0,
				number: 1,
				velocity: 81,
				type: 'single',
			},
		],
	},
	{
		id: 'Effect__Flasher',
		label: 'Effect - Flasher',
		isLogical: false,
		type: 'indexed',
		enum: 'Flasher',
		class: 'global',
		values: [
			{
				id: 'Off',
				label: 'Off',
				channel: 0,
				number: 1,
				velocity: 83,
				type: 'single',
			},
			{
				id: 'Audio Link',
				label: 'Audio Link',
				channel: 0,
				number: 1,
				velocity: 84,
				type: 'single',
			},
			{
				id: 'Random Audio Link',
				label: 'Random Audio Link',
				channel: 0,
				number: 1,
				velocity: 85,
				type: 'single',
			},
			{
				id: 'Hard Audio Link',
				label: 'Hard Audio Link',
				channel: 0,
				number: 1,
				velocity: 86,
				type: 'single',
			},
			{
				id: 'Random',
				label: 'Random',
				channel: 0,
				number: 1,
				velocity: 87,
				type: 'single',
			},
			{
				id: 'Hard',
				label: 'Hard',
				channel: 0,
				number: 1,
				velocity: 88,
				type: 'single',
			},
			{
				id: 'RESERVED',
				label: 'RESERVED',
				channel: 0,
				number: 1,
				velocity: 89,
				type: 'single',
			},
			{
				id: 'RESERVED',
				label: 'RESERVED',
				channel: 0,
				number: 1,
				velocity: 90,
				type: 'single',
			},
		],
	},
	{
		id: 'Effect__Moving Head Strobe',
		label: 'Effect - Moving Head Strobe',
		isLogical: false,
		type: 'indexed',
		enum: 'MovingHeadStrobe',
		class: 'global',
		values: [
			{
				id: 'Off',
				label: 'Off',
				channel: 0,
				number: 1,
				velocity: 91,
				type: 'single',
			},
			{
				id: 'Random',
				label: 'Random',
				channel: 0,
				number: 1,
				velocity: 92,
				type: 'single',
			},
			{
				id: 'Section Random',
				label: 'Section Random',
				channel: 0,
				number: 1,
				velocity: 93,
				type: 'single',
			},
			{
				id: 'Hard',
				label: 'Hard',
				channel: 0,
				number: 1,
				velocity: 94,
				type: 'single',
			},
		],
	},
	{
		id: 'Advanced__Screen Mapping',
		label: 'Advanced - Screen Mapping',
		isLogical: false,
		type: 'indexed',
		enum: 'ScreenMapping',
		class: 'global',
		values: [
			{
				id: 'Full',
				label: 'Full',
				channel: 0,
				number: 1,
				velocity: 95,
				type: 'single',
			},
			{
				id: 'Cropped DMX',
				label: 'Cropped DMX',
				channel: 0,
				number: 1,
				velocity: 96,
				type: 'single',
			},
			{
				id: 'Mapped',
				label: 'Mapped',
				channel: 0,
				number: 1,
				velocity: 97,
				type: 'single',
			},
			{
				id: 'RESERVED',
				label: 'RESERVED',
				channel: 0,
				number: 1,
				velocity: 98,
				type: 'single',
			},
		],
	},
	{
		id: 'Advanced__Wall Line Colors',
		label: 'Advanced - Wall Line Colors',
		isLogical: false,
		type: 'indexed',
		enum: 'WallLineColors',
		class: 'global',
		values: [
			{
				id: 'Initialize',
				label: 'Initialize',
				channel: 0,
				number: 1,
				velocity: 99,
				type: 'single',
			},
			{
				id: 'Deepsea',
				label: 'Deepsea',
				channel: 0,
				number: 1,
				velocity: 100,
				type: 'single',
			},
			{
				id: 'Skyhigh',
				label: 'Skyhigh',
				channel: 0,
				number: 1,
				velocity: 101,
				type: 'single',
			},
			{
				id: 'Lavender',
				label: 'Lavender',
				channel: 0,
				number: 1,
				velocity: 102,
				type: 'single',
			},
			{
				id: 'Lovepotion',
				label: 'Lovepotion',
				channel: 0,
				number: 1,
				velocity: 103,
				type: 'single',
			},
			{
				id: 'Yumekawa',
				label: 'Yumekawa',
				channel: 0,
				number: 1,
				velocity: 104,
				type: 'single',
			},
			{
				id: 'Sunset',
				label: 'Sunset',
				channel: 0,
				number: 1,
				velocity: 105,
				type: 'single',
			},
			{
				id: 'Goldenage',
				label: 'Goldenage',
				channel: 0,
				number: 1,
				velocity: 106,
				type: 'single',
			},
			{
				id: 'Redlight',
				label: 'Redlight',
				channel: 0,
				number: 1,
				velocity: 107,
				type: 'single',
			},
			{
				id: 'Takefive',
				label: 'Takefive',
				channel: 0,
				number: 1,
				velocity: 108,
				type: 'single',
			},
			{
				id: 'Garden',
				label: 'Garden',
				channel: 0,
				number: 1,
				velocity: 109,
				type: 'single',
			},
			{
				id: 'Energize',
				label: 'Energize',
				channel: 0,
				number: 1,
				velocity: 110,
				type: 'single',
			},
			{
				id: 'Happy',
				label: 'Happy',
				channel: 0,
				number: 1,
				velocity: 111,
				type: 'single',
			},
			{
				id: 'Poppinshower',
				label: 'Poppinshower',
				channel: 0,
				number: 1,
				velocity: 112,
				type: 'single',
			},
			{
				id: 'RGB',
				label: 'RGB',
				channel: 0,
				number: 1,
				velocity: 113,
				type: 'single',
			},
			{
				id: 'Turquise',
				label: 'Turquise',
				channel: 0,
				number: 1,
				velocity: 114,
				type: 'single',
			},
		],
	},
	{
		id: 'Activation__Wash Band',
		label: 'Activation - Wash Band',
		isLogical: true,
		type: 'indexed',
		enum: 'WashBand',
		class: 'logical',
		values: [
			{
				id: 'Always on',
				label: 'Always on',
				channel: 0,
				number: 38,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: 'Bass',
				label: 'Bass',
				channel: 0,
				number: 38,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: 'Low Mid',
				label: 'Low Mid',
				channel: 0,
				number: 39,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: 'Upper Mid',
				label: 'Upper Mid',
				channel: 0,
				number: 39,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: 'Treble',
				label: 'Treble',
				channel: 0,
				number: 39,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
		],
	},
	{
		id: 'Activation__Spot Band',
		label: 'Activation - Spot Band',
		isLogical: true,
		type: 'indexed',
		enum: 'SpotBand',
		class: 'logical',
		values: [
			{
				id: 'Always on',
				label: 'Always on',
				channel: 0,
				number: 39,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: 'Bass',
				label: 'Bass',
				channel: 0,
				number: 40,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: 'Low Mid',
				label: 'Low Mid',
				channel: 0,
				number: 40,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: 'Upper Mid',
				label: 'Upper Mid',
				channel: 0,
				number: 40,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: 'Treble',
				label: 'Treble',
				channel: 0,
				number: 40,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
		],
	},
	{
		id: 'Activation__Laser Band',
		label: 'Activation - Laser Band',
		isLogical: true,
		type: 'indexed',
		enum: 'LaserBand',
		class: 'logical',
		values: [
			{
				id: 'Always on',
				label: 'Always on',
				channel: 0,
				number: 41,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: 'Bass',
				label: 'Bass',
				channel: 0,
				number: 41,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: 'Low Mid',
				label: 'Low Mid',
				channel: 0,
				number: 41,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: 'Upper Mid',
				label: 'Upper Mid',
				channel: 0,
				number: 41,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: 'Treble',
				label: 'Treble',
				channel: 0,
				number: 42,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
		],
	},
	{
		id: 'General__Gobo',
		label: 'General - Gobo',
		isLogical: true,
		type: 'indexed',
		enum: 'Gobo',
		class: 'logical',
		values: [
			{
				id: '0',
				label: '0',
				channel: 0,
				number: 42,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: '1',
				label: '1',
				channel: 0,
				number: 42,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '2',
				label: '2',
				channel: 0,
				number: 42,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '3',
				label: '3',
				channel: 0,
				number: 43,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '4',
				label: '4',
				channel: 0,
				number: 43,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: '5',
				label: '5',
				channel: 0,
				number: 43,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '6',
				label: '6',
				channel: 0,
				number: 43,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '7',
				label: '7',
				channel: 0,
				number: 44,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
		],
	},
	{
		id: 'General__Set Spot to Color',
		label: 'General - Set Spot to Color',
		isLogical: true,
		type: 'indexed',
		enum: 'SpotColor',
		class: 'logical',
		values: [
			{
				id: '0',
				label: '0',
				channel: 0,
				number: 44,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '1',
				label: '1',
				channel: 0,
				number: 44,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '2',
				label: '2',
				channel: 0,
				number: 45,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '3',
				label: '3',
				channel: 0,
				number: 45,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: '4',
				label: '4',
				channel: 0,
				number: 45,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '5',
				label: '5',
				channel: 0,
				number: 45,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '6',
				label: '6',
				channel: 0,
				number: 46,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '7',
				label: '7',
				channel: 0,
				number: 46,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: '8',
				label: '8',
				channel: 0,
				number: 46,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '9',
				label: '9',
				channel: 0,
				number: 46,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '10',
				label: '10',
				channel: 0,
				number: 47,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '11',
				label: '11',
				channel: 0,
				number: 47,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: '12',
				label: '12',
				channel: 0,
				number: 47,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '13',
				label: '13',
				channel: 0,
				number: 47,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '14',
				label: '14',
				channel: 0,
				number: 48,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '15',
				label: '15',
				channel: 0,
				number: 48,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
		],
	},
	{
		id: 'General__Set Wash to Color',
		label: 'General - Set Wash to Color',
		isLogical: true,
		type: 'indexed',
		enum: 'WashColor',
		class: 'logical',
		values: [
			{
				id: '0',
				label: '0',
				channel: 0,
				number: 48,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '1',
				label: '1',
				channel: 0,
				number: 48,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '2',
				label: '2',
				channel: 0,
				number: 49,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '3',
				label: '3',
				channel: 0,
				number: 49,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: '4',
				label: '4',
				channel: 0,
				number: 49,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '5',
				label: '5',
				channel: 0,
				number: 49,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '6',
				label: '6',
				channel: 0,
				number: 50,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '7',
				label: '7',
				channel: 0,
				number: 50,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: '8',
				label: '8',
				channel: 0,
				number: 50,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '9',
				label: '9',
				channel: 0,
				number: 50,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '10',
				label: '10',
				channel: 0,
				number: 51,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '11',
				label: '11',
				channel: 0,
				number: 51,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: '12',
				label: '12',
				channel: 0,
				number: 51,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '13',
				label: '13',
				channel: 0,
				number: 51,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '14',
				label: '14',
				channel: 0,
				number: 52,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '15',
				label: '15',
				channel: 0,
				number: 52,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
		],
	},
	{
		id: 'General__Set Laser to Color',
		label: 'General - Set Laser to Color',
		isLogical: true,
		type: 'indexed',
		enum: 'LaserColor',
		class: 'logical',
		values: [
			{
				id: '0',
				label: '0',
				channel: 0,
				number: 52,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '1',
				label: '1',
				channel: 0,
				number: 52,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '2',
				label: '2',
				channel: 0,
				number: 53,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '3',
				label: '3',
				channel: 0,
				number: 53,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: '4',
				label: '4',
				channel: 0,
				number: 53,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '5',
				label: '5',
				channel: 0,
				number: 53,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '6',
				label: '6',
				channel: 0,
				number: 54,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '7',
				label: '7',
				channel: 0,
				number: 54,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: '8',
				label: '8',
				channel: 0,
				number: 54,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '9',
				label: '9',
				channel: 0,
				number: 54,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '10',
				label: '10',
				channel: 0,
				number: 55,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '11',
				label: '11',
				channel: 0,
				number: 55,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
			{
				id: '12',
				label: '12',
				channel: 0,
				number: 55,
				velocity: 64,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 64,
					end: 95,
				},
			},
			{
				id: '13',
				label: '13',
				channel: 0,
				number: 55,
				velocity: 96,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 96,
					end: 127,
				},
			},
			{
				id: '14',
				label: '14',
				channel: 0,
				number: 56,
				velocity: 0,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 0,
					end: 31,
				},
			},
			{
				id: '15',
				label: '15',
				channel: 0,
				number: 56,
				velocity: 32,
				type: 'ranged',
				range: {
					variable: 'velocity',
					start: 32,
					end: 63,
				},
			},
		],
	},
] as const

export default enums
