export interface FeedbackMappings {
	number: number
	name: string
	hasSections: 'None' | 'Logical' | 'Section' | 'Side' | 'SetColor' | 'Color' | 'AudioLink'
	type: 'Toggle' | 'Slider' | 'Enum'
	data: '0-1' | '0-4' | '0-7' | '0-15' | '0-127'
}

export const feedbackMappings: FeedbackMappings[] = [
	{
		number: 1,
		name: 'AllowPortals',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 2,
		name: 'Blackout',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 3,
		name: 'BlinderIntensity',
		hasSections: 'None',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 4,
		name: 'CleanLight',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 5,
		name: 'DiscoBall',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 6,
		name: 'Flasher',
		hasSections: 'None',
		type: 'Enum',
		data: '0-7',
	},
	{
		number: 7,
		name: 'FlasherIntensity',
		hasSections: 'None',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 8,
		name: 'FlasherSpeed',
		hasSections: 'None',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 9,
		name: 'GlobalIntensity',
		hasSections: 'None',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 10,
		name: 'Gobo',
		hasSections: 'Logical',
		type: 'Enum',
		data: '0-7',
	},
	{
		number: 11,
		name: 'GoboSpinSpeed',
		hasSections: 'Logical',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 12,
		name: 'GoboSpinSpeedReverse',
		hasSections: 'Logical',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 13,
		name: 'LaserBand',
		hasSections: 'Logical',
		type: 'Enum',
		data: '0-4',
	},
	{
		number: 14,
		name: 'LaserColor',
		hasSections: 'Logical',
		type: 'Enum',
		data: '0-15',
	},
	{
		number: 15,
		name: 'LaserEnabled',
		hasSections: 'Logical',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 16,
		name: 'LaserIntensity',
		hasSections: 'None',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 17,
		name: 'MirrorBallInner',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 18,
		name: 'MirrorBallMiddle',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 19,
		name: 'MirrorBallOuter',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 20,
		name: 'MovementSpeed',
		hasSections: 'None',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 21,
		name: 'MovingHeadStrobe',
		hasSections: 'None',
		type: 'Enum',
		data: '0-4',
	},
	{
		number: 22,
		name: 'MovingHeadStrobeSpeed',
		hasSections: 'None',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 23,
		name: 'Random',
		hasSections: 'None',
		type: 'Enum',
		data: '0-4',
	},
	{
		number: 24,
		name: 'ScreenMapping',
		hasSections: 'None',
		type: 'Enum',
		data: '0-4',
	},
	{
		number: 25,
		name: 'SectionEnabled',
		hasSections: 'Logical',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 26,
		name: 'SpotBand',
		hasSections: 'Logical',
		type: 'Enum',
		data: '0-4',
	},
	{
		number: 27,
		name: 'SpotColor',
		hasSections: 'Logical',
		type: 'Enum',
		data: '0-15',
	},
	{
		number: 28,
		name: 'SpotEnabled',
		hasSections: 'Logical',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 29,
		name: 'SpotIntensity',
		hasSections: 'None',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 30,
		name: 'SpotMovement',
		hasSections: 'None',
		type: 'Enum',
		data: '0-7',
	},
	{
		number: 31,
		name: 'SpotWidth',
		hasSections: 'Logical',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 32,
		name: 'VeryPoorSign',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 33,
		name: 'WallLineBrightness',
		hasSections: 'None',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 34,
		name: 'WallLineColors',
		hasSections: 'None',
		type: 'Enum',
		data: '0-15',
	},
	{
		number: 35,
		name: 'WallLineSpeed',
		hasSections: 'None',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 36,
		name: 'WallLineTension',
		hasSections: 'None',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 37,
		name: 'WallLines',
		hasSections: 'None',
		type: 'Enum',
		data: '0-7',
	},
	{
		number: 38,
		name: 'WashBand',
		hasSections: 'Logical',
		type: 'Enum',
		data: '0-4',
	},
	{
		number: 39,
		name: 'WashColor',
		hasSections: 'Logical',
		type: 'Enum',
		data: '0-15',
	},
	{
		number: 40,
		name: 'WashEnabled',
		hasSections: 'Logical',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 41,
		name: 'WashIntensity',
		hasSections: 'None',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 42,
		name: 'WashMovement',
		hasSections: 'None',
		type: 'Enum',
		data: '0-4',
	},
	{
		number: 43,
		name: 'WashWidth',
		hasSections: 'Logical',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 44,
		name: 'MidiFeedback',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 45,
		name: 'MidiLog',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 46,
		name: 'SectionToggles',
		hasSections: 'Section',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 47,
		name: 'SideToggles',
		hasSections: 'Side',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 48,
		name: 'MacroBypassApply',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 49,
		name: 'MacroApplyManually',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 50,
		name: 'MacroSet',
		hasSections: 'None',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 51,
		name: 'SetColor',
		hasSections: 'SetColor',
		type: 'Toggle',
		data: '0-1',
	},
	{
		number: 52,
		name: 'Color',
		hasSections: 'Color',
		type: 'Slider',
		data: '0-127',
	},
	{
		number: 53,
		name: 'AudioLink',
		hasSections: 'AudioLink',
		type: 'Slider',
		data: '0-127',
	},
]

export default feedbackMappings
