/* eslint-disable */ // This file is automatically "generated"/copied by the update_mappings.mjs script. Sadly this cannot be done as a simple json import, because the typing of json imports in ts is simply too weak (matches that of non-'as const' types ?)
export const mappings = {
    "mappings": [
        {"class": "physical",   "channel":0,"number": 0, "velocity":0, "section": "Advanced", "name": "Section Floor", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "SectionToggles"}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":1, "section": "Advanced", "name": "Section Dancer Podium", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "SectionToggles"}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":2, "section": "Advanced", "name": "Section Screen Bottom", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "SectionToggles"}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":3, "section": "Advanced", "name": "Section Screen Side", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "SectionToggles"}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":4, "section": "Advanced", "name": "Section Screen Top", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "SectionToggles"}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":5, "section": "Advanced", "name": "Section In Screen", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "SectionToggles"}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":6, "section": "Advanced", "name": "Section Mirror Ball Inner", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "SectionToggles"}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":7, "section": "Advanced", "name": "Section Mirror Ball Outer", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "SectionToggles"}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":8, "section": "Advanced", "name": "Section Side Screen Top", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "SectionToggles"}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":9, "section": "Advanced", "name": "Section Side Screen Bottom", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "SectionToggles"}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":42, "section": "Macro", "name": "Apply", "affectedBy": {"value": null, "reason":  "Panel/Local Only"}, "type": {"value": "Button", "feedback":  null}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":43, "section": "Macro", "name": "Clear Apply", "affectedBy": {"value": null, "reason": "Panel/Local Only"}, "type":  {"value": "Button", "feedback":  null}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":44, "section": "Macro", "name": "Bypass Apply", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "MacroBypassApply"}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":45, "section": "Macro", "name": "Apply Manually", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "MacroApplyManually"}},
        {"class": "physical",   "channel":0,"number": 0, "velocity":46, "section": "Macro", "name": "Set Macro Toggle", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "MacroSet"}},
        {"class": "global",     "channel":0,"number": 0, "velocity":79, "section": "Effect", "name": "Confetti", "affectedBy": {"value": null, "reason": "Global Effect"}, "type":  {"value": "Button", "feedback":  null}},
        {"class": "global",     "channel":0,"number": 0, "velocity":80, "section": "Effect", "name": "Co2 Down", "affectedBy": {"value": null, "reason": "Global Effect"}, "type":  {"value": "Button", "feedback":  null}},
        {"class": "global",     "channel":0,"number": 0, "velocity":81, "section": "Effect", "name": "Co2 Up", "affectedBy": {"value": null, "reason": "Global Effect"}, "type":  {"value": "Button", "feedback":  null}},
        {"class": "global",     "channel":0,"number": 0, "velocity":82, "section": "Effect", "name": "Fire", "affectedBy": {"value": null, "reason": "Global Effect"}, "type":  {"value": "Button", "feedback":  null}},
        {"class": "global",     "channel":0,"number": 0, "velocity":83, "section": "Effect", "name": "Bubbles", "affectedBy": {"value": null, "reason": "Global Effect"}, "type":  {"value": "Button", "feedback":  null}},
        {"class": "global",     "channel":0,"number": 0, "velocity":84, "section": "Effect", "name": "Reset", "affectedBy": {"value": null, "reason": "Global Effect"}, "type":  {"value": "Button", "feedback":  null}},
        {"class": "global",     "channel":0,"number": 0, "velocity":111, "section": "Advanced", "name": "Side Left", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "SideToggles"}},
        {"class": "global",     "channel":0,"number": 0, "velocity":112, "section": "Advanced", "name": "Side Right", "affectedBy": {"value": null, "reason": "Panel/Local Only"},"type": {"value": "Toggle", "feedback": "SideToggles"}},
        {"class": "global",     "channel":0,"number": 1, "velocity":0, "section": "Activation", "name": "Section Enabled", "affectedBy": {"value": ["Advanced Section & Side"]}, "type": {"value": "Toggle", "feedback": null}},
        {"class": "global",     "channel":0,"number": 1, "velocity":1, "section": "Activation", "name": "Spot Enabled", "affectedBy": {"value": ["Advanced Section & Side"]}, "type": {"value": "Toggle", "feedback": null}},
        {"class": "global",     "channel":0,"number": 1, "velocity":2, "section": "Activation", "name": "Wash Enabled", "affectedBy": {"value": ["Advanced Section & Side"]}, "type": {"value": "Toggle", "feedback": null}},
        {"class": "global",     "channel":0,"number": 1, "velocity":3, "section": "Effect", "name": "Laser Enabled", "affectedBy": {"value": ["Advanced Section & Side"]}, "type": {"value": "Toggle", "feedback": null}},
        {"class": "midi",       "channel":0,"number": 1, "velocity": 20, "section": "Midi Only", "name": "Write `[Neoluma][Midi] Pong` to Log, if Ready", "affectedBy": {"value": null, "reason": "Stateless"}, "type": {"value": "Button", "feedback": null}},
        {"class": "physical",   "channel":0,"number": 1, "velocity": 21, "section": "General", "name": "Set Value to Color (for Color Buttons)", "affectedBy": {"value": null, "reason": "Panel/Local Only"}, "type": {"value": "Toggle", "feedback": "SetColor"}},
        {"class": "physical",   "channel":0,"number": 1, "velocity": 22, "section": "General", "name": "Set Spot Color", "affectedBy": {"value": null, "reason": "Panel/Local Only"}, "type": {"value": "Toggle", "feedback": "SetColor"}},
        {"class": "physical",   "channel":0,"number": 1, "velocity": 23, "section": "General", "name": "Set Wash Color", "affectedBy": {"value": null, "reason": "Panel/Local Only"}, "type": {"value": "Toggle", "feedback": "SetColor"}},
        {"class": "physical",   "channel":0,"number": 1, "velocity": 24, "section": "General", "name": "Set Laser Color", "affectedBy": {"value": null, "reason": "Panel/Local Only"}, "type": {"value": "Toggle", "feedback": "SetColor"}},
        {"class": "physical",   "channel":0,"number": 1, "velocity": 48, "section": "General", "name": "Gobo Spin Speed Reverse", "affectedBy": {"value": ["Advanced Section & Side"]}, "type": {"value": "Toggle", "feedback": null}},
        {"class": "global",     "channel":0,"number": 1, "velocity": 57, "section": "Advanced", "name": "Force Resync All", "affectedBy": {"value": null, "reason": "Global"}, "type": {"value": "Button", "feedback": null}},
        {"class": "global",     "channel":0,"number": 1, "velocity": 58, "section": "Advanced", "name": "Allow Portals", "affectedBy": {"value": null, "reason": "Global"}, "type": {"value": "Toggle", "feedback": "AllowPortals"}},
        {"class": "global",     "channel":0,"number": 1, "velocity": 59, "section": "Advanced", "name": "Clean Light", "affectedBy": {"value": null, "reason": "Global"}, "type": {"value": "Toggle", "feedback": "CleanLight"}},
        {"class": "global",     "channel":0,"number": 1, "velocity": 60, "section": "Advanced", "name": "Very Poor Sign", "affectedBy": {"value": null, "reason": "Global"}, "type": {"value": "Toggle", "feedback": "VeryPoorSign"}},
        {"class": "global",     "channel":0,"number": 1, "velocity": 61, "section": "Advanced", "name": "RESERVED", "affectedBy": {"value": null, "reason": "Global"}, "type": {"value": "Toggle", "feedback": null}},
        {"class": "global",     "channel":0,"number": 1, "velocity": 62, "section": "Activation", "name": "Disco Ball", "affectedBy": {"value": null, "reason": "Global"}, "type": {"value": "Toggle", "feedback": "DiscoBall"}},
        {"class": "global",     "channel":0,"number": 1, "velocity": 63, "section": "Activation", "name": "Mirror Ball Inner", "affectedBy": {"value": null, "reason": "Global"}, "type": {"value": "Toggle", "feedback": "MirrorBallInner"}},
        {"class": "global",     "channel":0,"number": 1, "velocity": 64, "section": "Activation", "name": "Mirror Ball Middle", "affectedBy": {"value": null, "reason": "Global"}, "type": {"value": "Toggle", "feedback": "MirrorBallMiddle"}},
        {"class": "global",     "channel":0,"number": 1, "velocity": 65, "section": "Activation", "name": "Mirror Ball Outer", "affectedBy": {"value": null, "reason": "Global"}, "type": {"value": "Toggle", "feedback": "MirrorBallOuter"}},
        {"class": "global",     "channel":0,"number": 1, "velocity": 82, "section": "General", "name": "Blackout", "affectedBy": {"value": null, "reason": "Global"}, "type": {"value": "Toggle", "feedback": "Blackout"}},
        {"class": "global",     "channel":0,"number": 1, "velocity": 115, "section": "AudioLink", "name": "Reset Settings", "affectedBy": {"value": null, "reason": "Global"}, "type": {"value": "Button", "feedback": null}},
        {"class": "global",     "channel":0,"number": 1, "velocity": 116, "section": "AudioLink Smoothing", "name": "Reset Settings", "affectedBy": {"value": null, "reason": "Global"}, "type": {"value": "Button", "feedback": null}},
        {"class": "physical",   "channel":0,"number": 1, "velocity": 117, "section": "General", "name": "UI Larger", "affectedBy": {"value": null, "reason": "Panel Only"}, "type": {"value": "Button", "feedback": null}},
        {"class": "physical",   "channel":0,"number": 1, "velocity": 118, "section": "General", "name": "UI Smaller", "affectedBy": {"value": null, "reason": "Panel Only"}, "type": {"value": "Button", "feedback": null}},
        {"class": "midi",       "channel":0,"number": 1, "velocity": 119, "section": "Midi Only", "name": "Log received and processed Midi events", "affectedBy": {"value": null, "reason": "Stateless"}, "type": {"value": "Toggle", "feedback": "MidiLog"}},
        {"class": "midi",       "channel":0,"number": 1, "velocity": 120, "section": "Midi Only", "name": "Midi Feedback", "affectedBy": {"value": null, "reason": "Stateless"}, "type": {"value": "Toggle", "feedback": "MidiFeedback"}},
        {"class": "midi",       "channel":0,"number": 1, "velocity": 121, "section": "Midi Only", "name": "Dump All State as Feedback", "affectedBy": {"value": null, "reason": "Stateless"}, "type": {"value": "Button", "feedback": null}},
        {"class": "physical",   "channel":0,"number": 1, "velocity": 122, "section": "General", "name": "Gobo Spin Speed Reverse", "affectedBy": {"value": ["Advanced Section & Side"]}, "type": {"value": "Toggle", "feedback": null}},
        {"class": "physical",   "channel":0,"number": 2, "section": "General", "name": "Color R", "affectedBy": {"value": null, "reason": "Panel Only"}, "type": {"value": "Slider", "feedback": "Color"}},
        {"class": "physical",   "channel":0,"number": 3, "section": "General", "name": "Color G", "affectedBy": {"value": null, "reason": "Panel Only"}, "type": {"value": "Slider", "feedback": "Color"}},
        {"class": "physical",   "channel":0,"number": 4, "section": "General", "name": "Color B", "affectedBy": {"value": null, "reason": "Panel Only"}, "type": {"value": "Slider", "feedback": "Color"}},
        {"class": "physical",   "channel":0,"number": 5, "section": "General", "name": "Spot Width", "affectedBy": {"value": ["Advanced Section & Side"]}, "type": {"value": "Slider", "feedback": "SpotWidth"}},
        {"class": "physical",   "channel":0,"number": 6, "section": "General", "name": "Wash Width", "affectedBy": {"value": ["Advanced Section & Side"]}, "type": {"value": "Slider", "feedback": "WashWidth"}},
        {"class": "physical",   "channel":0,"number": 7, "section": "General", "name": "Gobo Spin Speed", "affectedBy": {"value": ["Advanced Section & Side"]}, "type": {"value": "Slider", "feedback": "GoboSpinSpeed"}},
        {"class": "global",     "channel":0,"number": 8, "section": "Wall Line Activation", "name": "Wall Line Speed", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "WallLineSpeed"}},
        {"class": "global",     "channel":0,"number": 9, "section": "Wall Line Activation", "name": "Wall Line Tension", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "WallLineTension"}},
        {"class": "global",     "channel":0,"number": 10, "section": "Wall Line Activation", "name": "Wall Line Brightness", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "WallLineBrightness"}},
        {"class": "global",     "channel":0,"number": 11, "section": "Movement", "name": "Movement Speed", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "MovementSpeed"}},
        {"class": "global",     "channel":0,"number": 12, "section": "Effect", "name": "Flasher Speed", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "FlasherSpeed"}},
        {"class": "global",     "channel":0,"number": 13, "section": "Effect", "name": "Moving Head Strobe Speed", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "MovingHeadStrobeSpeed"}},
        {"class": "global",     "channel":0,"number": 14, "section": "Intensity", "name": "Global Intensity", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "GlobalIntensity"}},
        {"class": "global",     "channel":0,"number": 15, "section": "Intensity", "name": "Spot Intensity", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "SpotIntensity"}},
        {"class": "global",     "channel":0,"number": 16, "section": "Intensity", "name": "Wash Intensity", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "WashIntensity"}},
        {"class": "global",     "channel":0,"number": 17, "section": "Intensity", "name": "Blinder Intensity", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "BlinderIntensity"}},
        {"class": "global",     "channel":0,"number": 18, "section": "Intensity", "name": "Flasher Intensity", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "FlasherIntensity"}},
        {"class": "global",     "channel":0,"number": 19, "section": "Intensity", "name": "Laser Intensity", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "LaserIntensity"}},
        {"class": "global",     "channel":0,"number": 20, "section": "AudioLink", "name": "Threshold Bass", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 21, "section": "AudioLink", "name": "Threshold Low Mid", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 22, "section": "AudioLink", "name": "Threshold Upper Mid", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 23, "section": "AudioLink", "name": "Threshold Treble", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 24, "section": "AudioLink", "name": "X Divider Nothing <-> Bass", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 25, "section": "AudioLink", "name": "X Divider Bass <-> Low Mid", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 26, "section": "AudioLink", "name": "X Divider Low Mid <-> Upper Mid", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 27, "section": "AudioLink", "name": "X Divider Upper Mid <-> Treble", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 28, "section": "AudioLink", "name": "Gain", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 29, "section": "AudioLink", "name": "Treble", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 30, "section": "AudioLink", "name": "Bass", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 31, "section": "AudioLink", "name": "Hit Fade Length", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 32, "section": "AudioLink", "name": "Hit Fade Exp. Falloff", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 33, "section": "AudioLink Smoothing", "name": "Bass Smoothing", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 34, "section": "AudioLink Smoothing", "name": "Lower Mid Smoothing", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 35, "section": "AudioLink Smoothing", "name": "Upper Mid Smoothing", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}},
        {"class": "global",     "channel":0,"number": 36, "section": "AudioLink Smoothing", "name": "Treble Smoothing", "affectedBy": {"value": null, "reason": "Global Slider"}, "type": {"value": "Slider", "feedback": "AudioLink"}}
    ],
    "indexedMappings": [
        {
            "class": "physical",
            "section": "Macro",
            "name": "Macro",
            "affectedBy": {"value": ["Set Macro Toggle"], "reason": null},
            "type":  {"value": "Button", "feedback":  null},
            "values": [
                {"channel":0,"number": 0, "velocity":47},
                {"channel":0,"number": 0, "velocity":48},
                {"channel":0,"number": 0, "velocity":49},
                {"channel":0,"number": 0, "velocity":50},
                {"channel":0,"number": 0, "velocity":51},
                {"channel":0,"number": 0, "velocity":52},
                {"channel":0,"number": 0, "velocity":53},
                {"channel":0,"number": 0, "velocity":54},
                {"channel":0,"number": 0, "velocity":55},
                {"channel":0,"number": 0, "velocity":56},
                {"channel":0,"number": 0, "velocity":57},
                {"channel":0,"number": 0, "velocity":58},
                {"channel":0,"number": 0, "velocity":59},
                {"channel":0,"number": 0, "velocity":60},
                {"channel":0,"number": 0, "velocity":61},
                {"channel":0,"number": 0, "velocity":62},
                {"channel":0,"number": 0, "velocity":63},
                {"channel":0,"number": 0, "velocity":64},
                {"channel":0,"number": 0, "velocity":65},
                {"channel":0,"number": 0, "velocity":66},
                {"channel":0,"number": 0, "velocity":67},
                {"channel":0,"number": 0, "velocity":68},
                {"channel":0,"number": 0, "velocity":69},
                {"channel":0,"number": 0, "velocity":70},
                {"channel":0,"number": 0, "velocity":71},
                {"channel":0,"number": 0, "velocity":72},
                {"channel":0,"number": 0, "velocity":73},
                {"channel":0,"number": 0, "velocity":74},
                {"channel":0,"number": 0, "velocity":75},
                {"channel":0,"number": 0, "velocity":76},
                {"channel":0,"number": 0, "velocity":77},
                {"channel":0,"number": 0, "velocity":78}
            ]
        },
        {
            "class": "physical",
            "section": "General",
            "name": "Color",
            "affectedBy": {"value": ["Advanced Section & Side", "General Set Spot Color", "General Set Wash Color", "General Set Laser Color", "General Set Value to Color"], "reason": null},
            "type": {"value": "Button", "feedback":  null},
            "values": [
                {"channel":0,"number": 1, "velocity": 4},
                {"channel":0,"number": 1, "velocity": 5},
                {"channel":0,"number": 1, "velocity": 6},
                {"channel":0,"number": 1, "velocity": 7},
                {"channel":0,"number": 1, "velocity": 8},
                {"channel":0,"number": 1, "velocity": 9},
                {"channel":0,"number": 1, "velocity": 10},
                {"channel":0,"number": 1, "velocity": 11},
                {"channel":0,"number": 1, "velocity": 12},
                {"channel":0,"number": 1, "velocity": 13},
                {"channel":0,"number": 1, "velocity": 14},
                {"channel":0,"number": 1, "velocity": 15},
                {"channel":0,"number": 1, "velocity": 16},
                {"channel":0,"number": 1, "velocity": 17},
                {"channel":0,"number": 1, "velocity": 18},
                {"channel":0,"number": 1, "velocity": 19}
            ]
        },
        {
            "class": "logical",
            "section": "Macro",
            "name": "Use Macro",
            "affectedBy": {"value": null, "reason": "Logical Mapping"},
            "type": {"value": "Button", "feedback": null},
            "values": [
                {"channel":0,"number": 37, "velocity": 0},
                {"channel":0,"number": 37, "velocity": 1},
                {"channel":0,"number": 37, "velocity": 2},
                {"channel":0,"number": 37, "velocity": 3},
                {"channel":0,"number": 37, "velocity": 4},
                {"channel":0,"number": 37, "velocity": 5},
                {"channel":0,"number": 37, "velocity": 6},
                {"channel":0,"number": 37, "velocity": 7},
                {"channel":0,"number": 37, "velocity": 8},
                {"channel":0,"number": 37, "velocity": 9},
                {"channel":0,"number": 37, "velocity": 10},
                {"channel":0,"number": 37, "velocity": 11},
                {"channel":0,"number": 37, "velocity": 12},
                {"channel":0,"number": 37, "velocity": 13},
                {"channel":0,"number": 37, "velocity": 14},
                {"channel":0,"number": 37, "velocity": 15},
                {"channel":0,"number": 37, "velocity": 16},
                {"channel":0,"number": 37, "velocity": 17},
                {"channel":0,"number": 37, "velocity": 18},
                {"channel":0,"number": 37, "velocity": 19},
                {"channel":0,"number": 37, "velocity": 20},
                {"channel":0,"number": 37, "velocity": 21},
                {"channel":0,"number": 37, "velocity": 22},
                {"channel":0,"number": 37, "velocity": 23},
                {"channel":0,"number": 37, "velocity": 24},
                {"channel":0,"number": 37, "velocity": 25},
                {"channel":0,"number": 37, "velocity": 26},
                {"channel":0,"number": 37, "velocity": 27},
                {"channel":0,"number": 37, "velocity": 28},
                {"channel":0,"number": 37, "velocity": 29},
                {"channel":0,"number": 37, "velocity": 30},
                {"channel":0,"number": 37, "velocity": 31}
            ]
        },
        {
            "class": "logical",
            "section": "Macro",
            "name": "Set Macro",
            "affectedBy": {"value": null, "reason": "Logical Mapping"},
            "type": {"value": "Button", "feedback": null},
            "values": [
                {"channel":0,"number": 37, "velocity": 32},
                {"channel":0,"number": 37, "velocity": 33},
                {"channel":0,"number": 37, "velocity": 34},
                {"channel":0,"number": 37, "velocity": 35},
                {"channel":0,"number": 37, "velocity": 36},
                {"channel":0,"number": 37, "velocity": 37},
                {"channel":0,"number": 37, "velocity": 38},
                {"channel":0,"number": 37, "velocity": 39},
                {"channel":0,"number": 37, "velocity": 40},
                {"channel":0,"number": 37, "velocity": 41},
                {"channel":0,"number": 37, "velocity": 42},
                {"channel":0,"number": 37, "velocity": 43},
                {"channel":0,"number": 37, "velocity": 44},
                {"channel":0,"number": 37, "velocity": 45},
                {"channel":0,"number": 37, "velocity": 46},
                {"channel":0,"number": 37, "velocity": 47},
                {"channel":0,"number": 37, "velocity": 48},
                {"channel":0,"number": 37, "velocity": 49},
                {"channel":0,"number": 37, "velocity": 50},
                {"channel":0,"number": 37, "velocity": 51},
                {"channel":0,"number": 37, "velocity": 52},
                {"channel":0,"number": 37, "velocity": 53},
                {"channel":0,"number": 37, "velocity": 54},
                {"channel":0,"number": 37, "velocity": 55},
                {"channel":0,"number": 37, "velocity": 56},
                {"channel":0,"number": 37, "velocity": 57},
                {"channel":0,"number": 37, "velocity": 58},
                {"channel":0,"number": 37, "velocity": 59},
                {"channel":0,"number": 37, "velocity": 60},
                {"channel":0,"number": 37, "velocity": 61},
                {"channel":0,"number": 37, "velocity": 62},
                {"channel":0,"number": 37, "velocity": 63}
            ]
        },
        {
            "class": "logical",
            "section": "General",
            "name": "Set Color",
            "affectedBy": { "value": null, "reason": "Logical Mapping"},
            "type": { "value": "Button", "feedback": null},
            "values": [
                {"channel":0, "number": 56, "velocity": 64},
                {"channel":0, "number": 56, "velocity": 65},
                {"channel":0, "number": 56, "velocity": 66},
                {"channel":0, "number": 56, "velocity": 67},
                {"channel":0, "number": 56, "velocity": 68},
                {"channel":0, "number": 56, "velocity": 69},
                {"channel":0, "number": 56, "velocity": 70},
                {"channel":0, "number": 56, "velocity": 71},
                {"channel":0, "number": 56, "velocity": 72},
                {"channel":0, "number": 56, "velocity": 73},
                {"channel":0, "number": 56, "velocity": 74},
                {"channel":0, "number": 56, "velocity": 75},
                {"channel":0, "number": 56, "velocity": 76},
                {"channel":0, "number": 56, "velocity": 77},
                {"channel":0, "number": 56, "velocity": 78},
                {"channel":0, "number": 56, "velocity": 79},
                {"channel":0, "number": 56, "velocity": 80},
                {"channel":0, "number": 56, "velocity": 81},
                {"channel":0, "number": 56, "velocity": 82},
                {"channel":0, "number": 56, "velocity": 83},
                {"channel":0, "number": 56, "velocity": 84},
                {"channel":0, "number": 56, "velocity": 85},
                {"channel":0, "number": 56, "velocity": 86},
                {"channel":0, "number": 56, "velocity": 87}
            ]
        },
        {
            "class": "physical",
            "section": "General",
            "name": "Gobo",
            "affectedBy": {"value": ["Advanced Section & Side"]},
            "type": {"value": "Button", "feedback": null},
            "values":  [
                {"channel":0, "number": 1, "velocity": 40},
                {"channel":0, "number": 1, "velocity": 41},
                {"channel":0, "number": 1, "velocity": 42},
                {"channel":0, "number": 1, "velocity": 43},
                {"channel":0, "number": 1, "velocity": 44},
                {"channel":0, "number": 1, "velocity": 45},
                {"channel":0, "number": 1, "velocity": 46},
                {"channel":0, "number": 1, "velocity": 47}
            ]
        },
        {
            "class": "physical",
            "section": "Activation",
            "name": "Wash Band",
            "affectedBy": {"value": ["Advanced Section & Side"]},
            "type": {"value": "Button", "feedback": null},
            "values": [
                {"channel":0, "number": 1, "velocity": 25, "name": "Always on"},
                {"channel":0, "number": 1, "velocity": 26, "name": "Bass"},
                {"channel":0, "number": 1, "velocity": 27, "name": "Low Mid"},
                {"channel":0, "number": 1, "velocity": 28, "name": "Upper Mid"},
                {"channel":0, "number": 1, "velocity": 29, "name": "Treble"}
            ]
        },
        {
            "class": "physical",
            "section": "Activation",
            "name": "Spot Band",
            "affectedBy": {"value": ["Advanced Section & Side"]},
            "type": {"value": "Button", "feedback": null},
            "values": [
                {"channel":0, "number": 1, "velocity": 30, "name": "Always on"},
                {"channel":0, "number": 1, "velocity": 31, "name": "Bass"},
                {"channel":0, "number": 1, "velocity": 32, "name": "Low Mid"},
                {"channel":0, "number": 1, "velocity": 33, "name": "Upper Mid"},
                {"channel":0, "number": 1, "velocity": 34, "name": "Treble"}
            ]
        },
        {
            "class": "physical",
            "section": "Activation",
            "name": "Laser Band",
            "affectedBy": {"value": ["Advanced Section & Side"]},
            "type": {"value": "Button", "feedback": null},
            "values": [
                {"channel":0, "number": 1, "velocity": 35, "name": "Always on"},
                {"channel":0, "number": 1, "velocity": 36, "name": "Bass"},
                {"channel":0, "number": 1, "velocity": 37, "name": "Low Mid"},
                {"channel":0, "number": 1, "velocity": 38, "name": "Upper Mid"},
                {"channel":0, "number": 1, "velocity": 39, "name": "Treble"}
            ]
        }
    ],
    "enumMappings": [
        {
            "class": "physical",
            "section": "Wall Line Activation",
            "name": "Wall Lines",
            "affectedBy": {"value": null, "reason": "Global"},
            "type": {"value": "Enum", "feedback": "WallLines"},
            "values": [
                {"channel":0, "number": 1, "velocity": 49, "name": "Fix"},
                {"channel":0, "number": 1, "velocity": 50, "name": "Audio Link"},
                {"channel":0, "number": 1, "velocity": 51, "name": "Wave Forward"},
                {"channel":0, "number": 1, "velocity": 52, "name": "Wave Center"},
                {"channel":0, "number": 1, "velocity": 53, "name": "Wave Up"},
                {"channel":0, "number": 1, "velocity": 54, "name": "Wave Down"},
                {"channel":0, "number": 1, "velocity": 55, "name": "Flash"},
                {"channel":0, "number": 1, "velocity": 56, "name": "RESERVED"}
            ]
        },

        {
            "class": "global",
            "section": "Movement",
            "name": "Spot Movement",
            "affectedBy": {"value": null, "reason": "Global"},
            "type": {"value": "Enum", "feedback": "SpotMovement"},
            "values": [
                {"channel":0, "number": 1, "velocity": 66, "name": "Static"},
                {"channel":0, "number": 1, "velocity": 67, "name": "Wave Forward"},
                {"channel":0, "number": 1, "velocity": 68, "name": "Wave Backward"},
                {"channel":0, "number": 1, "velocity": 69, "name": "Circle Backward"},
                {"channel":0, "number": 1, "velocity": 70, "name": "Circle Forward"},
                {"channel":0, "number": 1, "velocity": 71, "name": "Random"},
                {"channel":0, "number": 1, "velocity": 72, "name": "Strike"},
                {"channel":0, "number": 1, "velocity": 73, "name": "RESERVED"}
            ]
        },

        {
            "class": "global",
            "section": "Movement",
            "name": "Wash Movement",
            "affectedBy": {"value": null, "reason": "Global"},
            "type": {"value": "Enum", "feedback": "WashMovement"},
            "values": [
                {"channel":0, "number": 1, "velocity": 74, "name": "Static"},
                {"channel":0, "number": 1, "velocity": 75, "name": "Wash"},
                {"channel":0, "number": 1, "velocity": 76, "name": "Strike"},
                {"channel":0, "number": 1, "velocity": 77, "name": "RESERVED"}
            ]
        },

        {
            "class": "global",
            "section": "General",
            "name": "Random",
            "affectedBy": {"value": null, "reason": "Global"},
            "type": {"value": "Enum", "feedback": "Random"},
            "values": [
                {"channel":0, "number": 1, "velocity": 78, "name": "Off"},
                {"channel":0, "number": 1, "velocity": 79, "name": "Wave"},
                {"channel":0, "number": 1, "velocity": 80, "name": "Random"},
                {"channel":0, "number": 1, "velocity": 81, "name": "All"}
            ]
        },

        {
            "class": "global",
            "section": "Effect",
            "name": "Flasher",
            "affectedBy": {"value": null, "reason": "Global"},
            "type": {"value": "Enum", "feedback": "Flasher"},
            "values": [
                {"channel":0, "number": 1, "velocity": 83, "name": "Off"},
                {"channel":0, "number": 1, "velocity": 84, "name": "Audio Link"},
                {"channel":0, "number": 1, "velocity": 85, "name": "Random Audio Link"},
                {"channel":0, "number": 1, "velocity": 86, "name": "Hard Audio Link"},
                {"channel":0, "number": 1, "velocity": 87, "name": "Random"},
                {"channel":0, "number": 1, "velocity": 88, "name": "Hard"},
                {"channel":0, "number": 1, "velocity": 89, "name": "RESERVED"},
                {"channel":0, "number": 1, "velocity": 90, "name": "RESERVED"}
            ]
        },

        {
            "class": "global",
            "section": "Effect",
            "name": "Moving Head Strobe",
            "affectedBy": {"value": null, "reason": "Global"},
            "type": {"value": "Enum", "feedback": "MovingHeadStrobe"},
            "values": [
                {"channel":0, "number": 1, "velocity": 91, "name": "Off"},
                {"channel":0, "number": 1, "velocity": 92, "name": "Random"},
                {"channel":0, "number": 1, "velocity": 93, "name": "Section Random"},
                {"channel":0, "number": 1, "velocity": 94, "name": "Hard"}
            ]
        },

        {
            "class": "global",
            "section": "Advanced",
            "name": "Screen Mapping",
            "affectedBy": {"value": null, "reason": "Global"},
            "type": {"value": "Enum", "feedback": "ScreenMapping"},
            "values": [
                {"channel":0,"number": 1, "velocity": 95, "section": "Advanced", "name": "Full"},
                {"channel":0,"number": 1, "velocity": 96, "section": "Advanced", "name": "Cropped DMX"},
                {"channel":0,"number": 1, "velocity": 97, "section": "Advanced", "name": "Mapped"},
                {"channel":0,"number": 1, "velocity": 98, "section": "Advanced", "name": "RESERVED"}
            ]
        },

        {
            "class": "global",
            "section": "Advanced",
            "name": "Wall Line Colors",
            "affectedBy": {"value": null, "reason": "Global"},
            "type": {"value": "Enum", "feedback": "WallLineColors"},
            "values": [
                {"channel":0, "number": 1, "velocity": 99, "name": "Initialize"},
                {"channel":0, "number": 1, "velocity": 100, "name": "Deepsea"},
                {"channel":0, "number": 1, "velocity": 101, "name": "Skyhigh"},
                {"channel":0, "number": 1, "velocity": 102, "name": "Lavender"},
                {"channel":0, "number": 1, "velocity": 103, "name": "Lovepotion"},
                {"channel":0, "number": 1, "velocity": 104, "name": "Yumekawa"},
                {"channel":0, "number": 1, "velocity": 105, "name": "Sunset"},
                {"channel":0, "number": 1, "velocity": 106, "name": "Goldenage"},
                {"channel":0, "number": 1, "velocity": 107, "name": "Redlight"},
                {"channel":0, "number": 1, "velocity": 108, "name": "Takefive"},
                {"channel":0, "number": 1, "velocity": 109, "name": "Garden"},
                {"channel":0, "number": 1, "velocity": 110, "name": "Energize"},
                {"channel":0, "number": 1, "velocity": 111, "name": "Happy"},
                {"channel":0, "number": 1, "velocity": 112, "name": "Poppinshower"},
                {"channel":0, "number": 1, "velocity": 113, "name": "RGB"},
                {"channel":0, "number": 1, "velocity": 114, "name": "Turquise"}
            ]
        }
    ],
    "sectionNames": [
        "Floor",
        "DancerPodium",
        "ScreenBottom",
        "ScreenSide",
        "ScreenTop",
        "InScreen",
        "MirrorBallInner",
        "MirrorBallOuter",
        "SideScreenTop",
        "SideScreenBottom",
        "RESERVED"
    ],
    "sideNames": [
        "Left",
        "Right"
    ],
    "rangedNames": [
        {"index": 0, "section": "Floor", "side": "Left"},
        {"index": 1, "section": "Floor", "side": "Right"},
        {"index": 2, "section": "DancerPodium", "side": "Left"},
        {"index": 3, "section": "DancerPodium", "side": "Right"},
        {"index": 4, "section": "ScreenBottom", "side": "Left"},
        {"index": 5, "section": "ScreenBottom", "side": "Right"},
        {"index": 6, "section": "ScreenSide", "side": "Left"},
        {"index": 7, "section": "ScreenSide", "side": "Right"},
        {"index": 8, "section": "ScreenTop", "side": "Left"},
        {"index": 9, "section": "ScreenTop", "side": "Right"},
        {"index": 10, "section": "InScreen", "side": "Left"},
        {"index": 11, "section": "InScreen", "side": "Right"},
        {"index": 12, "section": "MirrorBallInner", "side": "Left"},
        {"index": 13, "section": "MirrorBallInner", "side": "Right"},
        {"index": 14, "section": "MirrorBallOuter", "side": "Left"},
        {"index": 15, "section": "MirrorBallOuter", "side": "Right"},
        {"index": 16, "section": "SideScreenTop", "side": "Left"},
        {"index": 17, "section": "SideScreenTop", "side": "Right"},
        {"index": 18, "section": "SideScreenBottom", "side": "Left"},
        {"index": 19, "section": "SideScreenBottom", "side": "Right"},
        {"index": 20, "section": "RESERVED", "side": "Left"},
        {"index": 21, "section": "RESERVED", "side": "Right"},
        {"index": 22, "section": "RESERVED", "side": "Left"},
        {"index": 23, "section": "RESERVED", "side": "Right"},
        {"index": 24, "section": "RESERVED", "side": "Left"},
        {"index": 25, "section": "RESERVED", "side": "Right"},
        {"index": 26, "section": "RESERVED", "side": "Left"},
        {"index": 27, "section": "RESERVED", "side": "Right"},
        {"index": 28, "section": "RESERVED", "side": "Left"},
        {"index": 29, "section": "RESERVED", "side": "Right"},
        {"index": 30, "section": "RESERVED", "side": "Left"},
        {"index": 31, "section": "RESERVED", "side": "Right"}
    ],
    "rangedMappings": [
        {"class": "logical", "channel":0,"number": 37, "velocity": {"start": 64, "end": 95}, "section": "Activation", "name": "Section Enabled", "affectedBy": {"value": null, "reason": "Logical Mapping"}, "type": {"value": "Toggle", "feedback": "SectionEnabled"}},
        {"class": "logical", "channel":0,"number": 37, "velocity": {"start": 96, "end": 127}, "section": "Activation", "name": "Spot Enabled", "affectedBy": {"value": null, "reason": "Logical Mapping"}, "type": {"value": "Toggle", "feedback": "SpotEnabled"}},
        {"class": "logical", "channel":0,"number": 38, "velocity": {"start": 0, "end": 31}, "section": "Activation", "name": "Wash Enabled", "affectedBy": {"value": null, "reason": "Logical Mapping"}, "type": {"value": "Toggle", "feedback": "WashEnabled"}},
        {"class": "logical", "channel":0,"number": 38, "velocity": {"start": 32, "end": 63}, "section": "Effect", "name": "Laser Enabled", "affectedBy": {"value": null, "reason": "Logical Mapping"}, "type": {"value": "Toggle", "feedback": "LaserEnabled"}},
        {"class": "logical", "channel":0,"number": 44, "velocity": {"start": 32, "end": 63}, "section": "General", "name": "Gobo Spin Speed Reverse", "affectedBy": {"value": null, "reason": "Logical Mapping"}, "type": {"value": "Toggle", "feedback": "GoboSpinSpeedReverse"}},
        {"class": "logical", "channel":0,"number": {"start": 64, "end": 95}, "section": "General", "name": "Spot Width", "affectedBy": {"value": null, "reason": "Logical Mapping"}, "type": {"value": "Slider", "feedback": "SpotWidth"}},
        {"class": "logical", "channel":0,"number": {"start": 96, "end": 127}, "section": "General", "name": "Wash Width", "affectedBy": {"value": null, "reason": "Logical Mapping"}, "type": {"value": "Slider", "feedback": "WashWidth"}},
        {"class": "logical", "channel":1,"number": {"start": 0, "end": 31}, "section": "General", "name": "Gobo Spin Speed", "affectedBy": {"value": null, "reason": "Logical Mapping"}, "type": {"value": "Slider", "feedback": "GoboSpinSpeed"}}
    ],
    "enumRangedMappings": [
        {
            "class": "logical",
            "section": "Activation",
            "name": "Wash Band",
            "affectedBy": {"value": null, "reason": "Logical Mapping"},
            "type": {"value": "Enum", "feedback": "WashBand"},
            "values": [
                {"channel":0, "number": 38, "velocity": {"start": 64, "end": 95}, "name": "Always on"},
                {"channel":0, "number": 38, "velocity": {"start": 96, "end": 127}, "name": "Bass"},
                {"channel":0, "number": 39, "velocity": {"start": 0, "end": 31}, "name": "Low Mid"},
                {"channel":0, "number": 39, "velocity": {"start": 32, "end": 63}, "name": "Upper Mid"},
                {"channel":0, "number": 39, "velocity": {"start": 64, "end": 95}, "name": "Treble"}
            ]
        },
        {
            "class": "logical",
            "section": "Activation",
            "name": "Spot Band",
            "affectedBy": {"value": null, "reason": "Logical Mapping"},
            "type": {"value": "Enum", "feedback": "SpotBand"},
            "values": [
                {"channel":0, "number": 39, "velocity": {"start": 96, "end": 127}, "name": "Always on"},
                {"channel":0, "number": 40, "velocity": {"start": 0, "end": 31}, "name": "Bass"},
                {"channel":0, "number": 40, "velocity": {"start": 32, "end": 63}, "name": "Low Mid"},
                {"channel":0, "number": 40, "velocity": {"start": 64, "end": 95}, "name": "Upper Mid"},
                {"channel":0, "number": 40, "velocity": {"start": 96, "end": 127}, "name": "Treble"}
            ]
        },
        {
            "class": "logical",
            "section": "Activation",
            "name": "Laser Band",
            "affectedBy": {"value": null, "reason": "Logical Mapping"},
            "type": {"value": "Enum", "feedback": "LaserBand"},
            "values": [
                {"channel":0, "number": 41, "velocity": {"start": 0, "end": 31}, "name": "Always on"},
                {"channel":0, "number": 41, "velocity": {"start": 32, "end": 63}, "name": "Bass"},
                {"channel":0, "number": 41, "velocity": {"start": 64, "end": 95}, "name": "Low Mid"},
                {"channel":0, "number": 41, "velocity": {"start": 96, "end": 127}, "name": "Upper Mid"},
                {"channel":0, "number": 42, "velocity": {"start": 0, "end": 31}, "name": "Treble"}
            ]
        },
        {
            "class": "logical",
            "section": "General",
            "name": "Gobo",
            "affectedBy": {"value": null, "reason": "Logical Mapping"},
            "type": {"value": "Enum", "feedback": "Gobo"},
            "values": [
                {"channel":0, "number": 42, "velocity": {"start": 32, "end": 63}, "name": "0"},
                {"channel":0, "number": 42, "velocity": {"start": 64, "end": 95}, "name": "1"},
                {"channel":0, "number": 42, "velocity": {"start": 96, "end": 127}, "name": "2"},
                {"channel":0, "number": 43, "velocity": {"start": 0, "end": 31}, "name": "3"},
                {"channel":0, "number": 43, "velocity": {"start": 32, "end": 63}, "name": "4"},
                {"channel":0, "number": 43, "velocity": {"start": 64, "end": 95}, "name": "5"},
                {"channel":0, "number": 43, "velocity": {"start": 96, "end": 127}, "name": "6"},
                {"channel":0, "number": 44, "velocity": {"start": 0, "end": 31}, "name": "7"}
            ]
        },


        {
            "class": "logical",
            "section": "General",
            "name": "Set Spot to Color",
            "affectedBy": {"value": null, "reason": "Logical Mapping"},
            "type": {"value": "Enum", "feedback": "SpotColor"},
            "values": [
                {"channel": 0,"number": 44, "velocity": {"start": 64, "end": 95}, "name": "0"},
                {"channel": 0,"number": 44, "velocity": {"start": 96, "end": 127}, "name": "1"},
                {"channel": 0,"number": 45, "velocity": {"start": 0, "end": 31}, "name": "2"},
                {"channel": 0,"number": 45, "velocity": {"start": 32, "end": 63}, "name": "3"},
                {"channel": 0,"number": 45, "velocity": {"start": 64, "end": 95}, "name": "4"},
                {"channel": 0,"number": 45, "velocity": {"start": 96, "end": 127}, "name": "5"},
                {"channel": 0,"number": 46, "velocity": {"start": 0, "end": 31}, "name": "6"},
                {"channel": 0,"number": 46, "velocity": {"start": 32, "end": 63}, "name": "7"},
                {"channel": 0,"number": 46, "velocity": {"start": 64, "end": 95}, "name": "8"},
                {"channel": 0,"number": 46, "velocity": {"start": 96, "end": 127}, "name": "9"},
                {"channel": 0,"number": 47, "velocity": {"start": 0, "end": 31}, "name": "10"},
                {"channel": 0,"number": 47, "velocity": {"start": 32, "end": 63}, "name": "11"},
                {"channel": 0,"number": 47, "velocity": {"start": 64, "end": 95}, "name": "12"},
                {"channel": 0,"number": 47, "velocity": {"start": 96, "end": 127}, "name": "13"},
                {"channel": 0,"number": 48, "velocity": {"start": 0, "end": 31}, "name": "14"},
                {"channel": 0,"number": 48, "velocity": {"start": 32, "end": 63}, "name": "15"}
            ]
        },

        {
            "class":  "logical",
            "section": "General",
            "name": "Set Wash to Color",
            "affectedBy": {"value": null, "reason": "Logical Mapping"},
            "type": {"value": "Enum", "feedback": "WashColor"},
            "values": [
                {"channel": 0,"number": 48, "velocity": {"start": 64, "end": 95}, "name": "0"},
                {"channel": 0,"number": 48, "velocity": {"start": 96, "end": 127}, "name": "1"},
                {"channel": 0,"number": 49, "velocity": {"start": 0, "end": 31}, "name": "2"},
                {"channel": 0,"number": 49, "velocity": {"start": 32, "end": 63}, "name": "3"},
                {"channel": 0,"number": 49, "velocity": {"start": 64, "end": 95}, "name": "4"},
                {"channel": 0,"number": 49, "velocity": {"start": 96, "end": 127}, "name": "5"},
                {"channel": 0,"number": 50, "velocity": {"start": 0, "end": 31}, "name": "6"},
                {"channel": 0,"number": 50, "velocity": {"start": 32, "end": 63}, "name": "7"},
                {"channel": 0,"number": 50, "velocity": {"start": 64, "end": 95}, "name": "8"},
                {"channel": 0,"number": 50, "velocity": {"start": 96, "end": 127}, "name": "9"},
                {"channel": 0,"number": 51, "velocity": {"start": 0, "end": 31}, "name": "10"},
                {"channel": 0,"number": 51, "velocity": {"start": 32, "end": 63}, "name": "11"},
                {"channel": 0,"number": 51, "velocity": {"start": 64, "end": 95}, "name": "12"},
                {"channel": 0,"number": 51, "velocity": {"start": 96, "end": 127}, "name": "13"},
                {"channel": 0,"number": 52, "velocity": {"start": 0, "end": 31}, "name": "14"},
                {"channel": 0,"number": 52, "velocity": {"start": 32, "end": 63}, "name": "15"}
            ]
        },

        {
            "class":  "logical",
            "section": "General",
            "name": "Set Laser to Color",
            "affectedBy": {"value": null, "reason": "Logical Mapping"},
            "type": {"value": "Enum", "feedback": "LaserColor"},
            "values": [
                {"channel": 0,"number": 52, "velocity": {"start": 64, "end": 95}, "name": "0"},
                {"channel": 0,"number": 52, "velocity": {"start": 96, "end": 127}, "name": "1"},
                {"channel": 0,"number": 53, "velocity": {"start": 0, "end": 31}, "name": "2"},
                {"channel": 0,"number": 53, "velocity": {"start": 32, "end": 63}, "name": "3"},
                {"channel": 0,"number": 53, "velocity": {"start": 64, "end": 95}, "name": "4"},
                {"channel": 0,"number": 53, "velocity": {"start": 96, "end": 127}, "name": "5"},
                {"channel": 0,"number": 54, "velocity": {"start": 0, "end": 31}, "name": "6"},
                {"channel": 0,"number": 54, "velocity": {"start": 32, "end": 63}, "name": "7"},
                {"channel": 0,"number": 54, "velocity": {"start": 64, "end": 95}, "name": "8"},
                {"channel": 0,"number": 54, "velocity": {"start": 96, "end": 127}, "name": "9"},
                {"channel": 0,"number": 55, "velocity": {"start": 0, "end": 31}, "name": "10"},
                {"channel": 0,"number": 55, "velocity": {"start": 32, "end": 63}, "name": "11"},
                {"channel": 0,"number": 55, "velocity": {"start": 64, "end": 95}, "name": "12"},
                {"channel": 0,"number": 55, "velocity": {"start": 96, "end": 127}, "name": "13"},
                {"channel": 0,"number": 56, "velocity": {"start": 0, "end": 31}, "name": "14"},
                {"channel": 0,"number": 56, "velocity": {"start": 32, "end": 63}, "name": "15"}
            ]
        }
    ],
    "feedbackNames": [
        "AllowPortals",
        "Blackout",
        "BlinderIntensity",
        "CleanLight",
        "DiscoBall",
        "Flasher",
        "FlasherIntensity",
        "FlasherSpeed",
        "GlobalIntensity",
        "Gobo",
        "GoboSpinSpeed",
        "GoboSpinSpeedReverse",
        "LaserBand",
        "LaserColor",
        "LaserEnabled",
        "LaserIntensity",
        "MirrorBallInner",
        "MirrorBallMiddle",
        "MirrorBallOuter",
        "MovementSpeed",
        "MovingHeadStrobe",
        "MovingHeadStrobeSpeed",
        "Random",
        "ScreenMapping",
        "SectionEnabled",
        "SpotBand",
        "SpotColor",
        "SpotEnabled",
        "SpotIntensity",
        "SpotMovement",
        "SpotWidth",
        "VeryPoorSign",
        "WallLineBrightness",
        "WallLineColors",
        "WallLineSpeed",
        "WallLineTension",
        "WallLines",
        "WashBand",
        "WashColor",
        "WashEnabled",
        "WashIntensity",
        "WashMovement",
        "WashWidth",
        "MidiFeedback",
        "MidiLog",
        "SectionToggles",
        "SideToggles",
        "MacroBypassApply",
        "MacroApplyManually",
        "MacroSet",
        "SetColor",
        "Color",
        "AudioLink"
    ],
    "feedback": [
        {"number": 1, "name": "AllowPortals", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 2, "name": "Blackout", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 3, "name": "BlinderIntensity", "sectionType": "None", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 4, "name": "CleanLight", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 5, "name": "DiscoBall", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 6, "name": "Flasher", "sectionType": "None", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 7}},
        {"number": 7, "name": "FlasherIntensity", "sectionType": "None", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 8, "name": "FlasherSpeed", "sectionType": "None", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 9, "name": "GlobalIntensity", "sectionType": "None", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 10, "name": "Gobo", "sectionType": "Logical", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 7}},
        {"number": 11, "name": "GoboSpinSpeed", "sectionType": "Logical", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 12, "name": "GoboSpinSpeedReverse", "sectionType": "Logical", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 13, "name": "LaserBand", "sectionType": "Logical", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 4}},
        {"number": 14, "name": "LaserColor", "sectionType": "Logical", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 15}},
        {"number": 15, "name": "LaserEnabled", "sectionType": "Logical", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 16, "name": "LaserIntensity", "sectionType": "None", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 17, "name": "MirrorBallInner", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 18, "name": "MirrorBallMiddle", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 19, "name": "MirrorBallOuter", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 20, "name": "MovementSpeed", "sectionType": "None", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 21, "name": "MovingHeadStrobe", "sectionType": "None", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 4}},
        {"number": 22, "name": "MovingHeadStrobeSpeed", "sectionType": "None", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 23, "name": "Random", "sectionType": "None", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 4}},
        {"number": 24, "name": "ScreenMapping", "sectionType": "None", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 4}},
        {"number": 25, "name": "SectionEnabled", "sectionType": "Logical", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 26, "name": "SpotBand", "sectionType": "Logical", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 4}},
        {"number": 27, "name": "SpotColor", "sectionType": "Logical", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 15}},
        {"number": 28, "name": "SpotEnabled", "sectionType": "Logical", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 29, "name": "SpotIntensity", "sectionType": "None", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 30, "name": "SpotMovement", "sectionType": "None", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 7}},
        {"number": 31, "name": "SpotWidth", "sectionType": "Logical", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 32, "name": "VeryPoorSign", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 33, "name": "WallLineBrightness", "sectionType": "None", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 34, "name": "WallLineColors", "sectionType": "None", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 15}},
        {"number": 35, "name": "WallLineSpeed", "sectionType": "None", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 36, "name": "WallLineTension", "sectionType": "None", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 37, "name": "WallLines", "sectionType": "None", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 7}},
        {"number": 38, "name": "WashBand", "sectionType": "Logical", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 4}},
        {"number": 39, "name": "WashColor", "sectionType": "Logical", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 15}},
        {"number": 40, "name": "WashEnabled", "sectionType": "Logical", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 41, "name": "WashIntensity", "sectionType": "None", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 42, "name": "WashMovement", "sectionType": "None", "type": "Enum", "data": {"type": "Range", "start": 0, "end": 4}},
        {"number": 43, "name": "WashWidth", "sectionType": "Logical", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 44, "name": "MidiFeedback", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 45, "name": "MidiLog", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 46, "name": "SectionToggles", "sectionType": "Section", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 47, "name": "SideToggles", "sectionType": "Side", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 48, "name": "MacroBypassApply", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 49, "name": "MacroApplyManually", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 50, "name": "MacroSet", "sectionType": "None", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 51, "name": "SetColor", "sectionType": "SetColor", "type": "Toggle", "data": {"type": "Bool", "start": 0, "end": 1}},
        {"number": 52, "name": "Color", "sectionType": "Color", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}},
        {"number": 53, "name": "AudioLink", "sectionType": "AudioLink", "type": "Slider", "data": {"type": "Range", "start": 0, "end": 127}}
    ]
} as const

export default mappings
