import type { SliderMappingData } from './mapping_data.js'

const ALL = 'ALL'

export const sliders: SliderMappingData[] = [
	{
		id: 'General__Color R',
		label: 'General - Color R',
		channel: 0,
		number: 2,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'Color',
		class: 'physical',
	},
	{
		id: 'General__Color G',
		label: 'General - Color G',
		channel: 0,
		number: 3,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'Color',
		class: 'physical',
	},
	{
		id: 'General__Color B',
		label: 'General - Color B',
		channel: 0,
		number: 4,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'Color',
		class: 'physical',
	},
	{
		id: 'General__Spot Width',
		label: 'General - Spot Width',
		channel: 0,
		number: 5,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'SpotWidth',
		class: 'physical',
	},
	{
		id: 'General__Wash Width',
		label: 'General - Wash Width',
		channel: 0,
		number: 6,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'WashWidth',
		class: 'physical',
	},
	{
		id: 'General__Gobo Spin Speed',
		label: 'General - Gobo Spin Speed',
		channel: 0,
		number: 7,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'GoboSpinSpeed',
		class: 'physical',
	},
	{
		id: 'Wall Line Activation__Wall Line Speed',
		label: 'Wall Line Activation - Wall Line Speed',
		channel: 0,
		number: 8,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'WallLineSpeed',
		class: 'global',
	},
	{
		id: 'Wall Line Activation__Wall Line Tension',
		label: 'Wall Line Activation - Wall Line Tension',
		channel: 0,
		number: 9,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'WallLineTension',
		class: 'global',
	},
	{
		id: 'Wall Line Activation__Wall Line Brightness',
		label: 'Wall Line Activation - Wall Line Brightness',
		channel: 0,
		number: 10,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'WallLineBrightness',
		class: 'global',
	},
	{
		id: 'Movement__Movement Speed',
		label: 'Movement - Movement Speed',
		channel: 0,
		number: 11,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'MovementSpeed',
		class: 'global',
	},
	{
		id: 'Effect__Flasher Speed',
		label: 'Effect - Flasher Speed',
		channel: 0,
		number: 12,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'FlasherSpeed',
		class: 'global',
	},
	{
		id: 'Effect__Moving Head Strobe Speed',
		label: 'Effect - Moving Head Strobe Speed',
		channel: 0,
		number: 13,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'MovingHeadStrobeSpeed',
		class: 'global',
	},
	{
		id: 'Intensity__Global Intensity',
		label: 'Intensity - Global Intensity',
		channel: 0,
		number: 14,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'GlobalIntensity',
		class: 'global',
	},
	{
		id: 'Intensity__Spot Intensity',
		label: 'Intensity - Spot Intensity',
		channel: 0,
		number: 15,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'SpotIntensity',
		class: 'global',
	},
	{
		id: 'Intensity__Wash Intensity',
		label: 'Intensity - Wash Intensity',
		channel: 0,
		number: 16,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'WashIntensity',
		class: 'global',
	},
	{
		id: 'Intensity__Blinder Intensity',
		label: 'Intensity - Blinder Intensity',
		channel: 0,
		number: 17,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'BlinderIntensity',
		class: 'global',
	},
	{
		id: 'Intensity__Flasher Intensity',
		label: 'Intensity - Flasher Intensity',
		channel: 0,
		number: 18,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'FlasherIntensity',
		class: 'global',
	},
	{
		id: 'Intensity__Laser Intensity',
		label: 'Intensity - Laser Intensity',
		channel: 0,
		number: 19,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'LaserIntensity',
		class: 'global',
	},
	{
		id: 'AudioLink__Threshold Bass',
		label: 'AudioLink - Threshold Bass',
		channel: 0,
		number: 20,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink__Threshold Low Mid',
		label: 'AudioLink - Threshold Low Mid',
		channel: 0,
		number: 21,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink__Threshold Upper Mid',
		label: 'AudioLink - Threshold Upper Mid',
		channel: 0,
		number: 22,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink__Threshold Treble',
		label: 'AudioLink - Threshold Treble',
		channel: 0,
		number: 23,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink__X Divider Nothing <-> Bass',
		label: 'AudioLink - X Divider Nothing <-> Bass',
		channel: 0,
		number: 24,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink__X Divider Bass <-> Low Mid',
		label: 'AudioLink - X Divider Bass <-> Low Mid',
		channel: 0,
		number: 25,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink__X Divider Low Mid <-> Upper Mid',
		label: 'AudioLink - X Divider Low Mid <-> Upper Mid',
		channel: 0,
		number: 26,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink__X Divider Upper Mid <-> Treble',
		label: 'AudioLink - X Divider Upper Mid <-> Treble',
		channel: 0,
		number: 27,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink__Gain',
		label: 'AudioLink - Gain',
		channel: 0,
		number: 28,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink__Treble',
		label: 'AudioLink - Treble',
		channel: 0,
		number: 29,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink__Bass',
		label: 'AudioLink - Bass',
		channel: 0,
		number: 30,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink__Hit Fade Length',
		label: 'AudioLink - Hit Fade Length',
		channel: 0,
		number: 31,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink__Hit Fade Exp. Falloff',
		label: 'AudioLink - Hit Fade Exp. Falloff',
		channel: 0,
		number: 32,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink Smoothing__Bass Smoothing',
		label: 'AudioLink Smoothing - Bass Smoothing',
		channel: 0,
		number: 33,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink Smoothing__Lower Mid Smoothing',
		label: 'AudioLink Smoothing - Lower Mid Smoothing',
		channel: 0,
		number: 34,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink Smoothing__Upper Mid Smoothing',
		label: 'AudioLink Smoothing - Upper Mid Smoothing',
		channel: 0,
		number: 35,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'AudioLink Smoothing__Treble Smoothing',
		label: 'AudioLink Smoothing - Treble Smoothing',
		channel: 0,
		number: 36,
		velocity: ALL,
		type: 'single',
		isLogical: false,
		enum: 'AudioLink',
		class: 'global',
	},
	{
		id: 'General__Spot Width',
		label: 'General - Spot Width',
		channel: 0,
		number: 64,
		velocity: 'ALL',
		type: 'ranged',
		isLogical: true,
		enum: 'SpotWidth',
		class: 'logical',
		range: {
			variable: 'number',
			start: 64,
			end: 95,
		},
	},
	{
		id: 'General__Wash Width',
		label: 'General - Wash Width',
		channel: 0,
		number: 96,
		velocity: 'ALL',
		type: 'ranged',
		isLogical: true,
		enum: 'WashWidth',
		class: 'logical',
		range: {
			variable: 'number',
			start: 96,
			end: 127,
		},
	},
	{
		id: 'General__Gobo Spin Speed',
		label: 'General - Gobo Spin Speed',
		channel: 1,
		number: 0,
		velocity: 'ALL',
		type: 'ranged',
		isLogical: true,
		enum: 'GoboSpinSpeed',
		class: 'logical',
		range: {
			variable: 'number',
			start: 0,
			end: 31,
		},
	},
]

export default sliders
