import type MappingData from './mapping_data.js'

export const toggles: MappingData[] = [
	{
		id: 'Advanced__Section Floor',
		label: 'Advanced - Section Floor',
		channel: 0,
		number: 0,
		velocity: 0,
		enum: 'SectionToggles',
	},
	{
		id: 'Advanced__Section Dancer Podium',
		label: 'Advanced - Section Dancer Podium',
		channel: 0,
		number: 0,
		velocity: 1,
		enum: 'SectionToggles',
	},
	{
		id: 'Advanced__Section Screen Bottom',
		label: 'Advanced - Section Screen Bottom',
		channel: 0,
		number: 0,
		velocity: 2,
		enum: 'SectionToggles',
	},
	{
		id: 'Advanced__Section Screen Side',
		label: 'Advanced - Section Screen Side',
		channel: 0,
		number: 0,
		velocity: 3,
		enum: 'SectionToggles',
	},
	{
		id: 'Advanced__Section Screen Top',
		label: 'Advanced - Section Screen Top',
		channel: 0,
		number: 0,
		velocity: 4,
		enum: 'SectionToggles',
	},
	{
		id: 'Advanced__Section In Screen',
		label: 'Advanced - Section In Screen',
		channel: 0,
		number: 0,
		velocity: 5,
		enum: 'SectionToggles',
	},
	{
		id: 'Advanced__Section Mirror Ball Inner',
		label: 'Advanced - Section Mirror Ball Inner',
		channel: 0,
		number: 0,
		velocity: 6,
		enum: 'SectionToggles',
	},
	{
		id: 'Advanced__Section Mirror Ball Outer',
		label: 'Advanced - Section Mirror Ball Outer',
		channel: 0,
		number: 0,
		velocity: 7,
		enum: 'SectionToggles',
	},
	{
		id: 'Advanced__Section Side Screen Top',
		label: 'Advanced - Section Side Screen Top',
		channel: 0,
		number: 0,
		velocity: 8,
		enum: 'SectionToggles',
	},
	{
		id: 'Advanced__Section Side Screen Bottom',
		label: 'Advanced - Section Side Screen Bottom',
		channel: 0,
		number: 0,
		velocity: 9,
		enum: 'SectionToggles',
	},
	{
		id: 'Macro__Bypass Apply',
		label: 'Macro - Bypass Apply',
		channel: 0,
		number: 0,
		velocity: 44,
		enum: 'MacroBypassApply',
	},
	{
		id: 'Macro__Apply Manually',
		label: 'Macro - Apply Manually',
		channel: 0,
		number: 0,
		velocity: 45,
		enum: 'MacroApplyManually',
	},
	{
		id: 'Macro__Set Macro Toggle',
		label: 'Macro - Set Macro Toggle',
		channel: 0,
		number: 0,
		velocity: 46,
		enum: 'MacroSet',
	},
	{
		id: 'Advanced__Side Left',
		label: 'Advanced - Side Left',
		channel: 0,
		number: 0,
		velocity: 111,
		enum: 'SideToggles',
	},
	{
		id: 'Advanced__Side Right',
		label: 'Advanced - Side Right',
		channel: 0,
		number: 0,
		velocity: 112,
		enum: 'SideToggles',
	},
	{
		id: 'General__Set Value to Color (for Color Buttons)',
		label: 'General - Set Value to Color (for Color Buttons)',
		channel: 0,
		number: 1,
		velocity: 21,
		enum: 'SetColor',
	},
	{
		id: 'General__Set Spot Color',
		label: 'General - Set Spot Color',
		channel: 0,
		number: 1,
		velocity: 22,
		enum: 'SetColor',
	},
	{
		id: 'General__Set Wash Color',
		label: 'General - Set Wash Color',
		channel: 0,
		number: 1,
		velocity: 23,
		enum: 'SetColor',
	},
	{
		id: 'General__Set Laser Color',
		label: 'General - Set Laser Color',
		channel: 0,
		number: 1,
		velocity: 24,
		enum: 'SetColor',
	},
	{
		id: 'Advanced__Allow Portals',
		label: 'Advanced - Allow Portals',
		channel: 0,
		number: 1,
		velocity: 58,
		enum: 'AllowPortals',
	},
	{
		id: 'Advanced__Clean Light',
		label: 'Advanced - Clean Light',
		channel: 0,
		number: 1,
		velocity: 59,
		enum: 'CleanLight',
	},
	{
		id: 'Advanced__Very Poor Sign',
		label: 'Advanced - Very Poor Sign',
		channel: 0,
		number: 1,
		velocity: 60,
		enum: 'VeryPoorSign',
	},
	{
		id: 'Advanced__RESERVED',
		label: 'Advanced - RESERVED',
		channel: 0,
		number: 1,
		velocity: 61,
		enum: '',
	},
	{
		id: 'Activation__Disco Ball',
		label: 'Activation - Disco Ball',
		channel: 0,
		number: 1,
		velocity: 62,
		enum: 'DiscoBall',
	},
	{
		id: 'Activation__Mirror Ball Inner',
		label: 'Activation - Mirror Ball Inner',
		channel: 0,
		number: 1,
		velocity: 63,
		enum: 'MirrorBallInner',
	},
	{
		id: 'Activation__Mirror Ball Middle',
		label: 'Activation - Mirror Ball Middle',
		channel: 0,
		number: 1,
		velocity: 64,
		enum: 'MirrorBallMiddle',
	},
	{
		id: 'Activation__Mirror Ball Outer',
		label: 'Activation - Mirror Ball Outer',
		channel: 0,
		number: 1,
		velocity: 65,
		enum: 'MirrorBallOuter',
	},
	{
		id: 'General__Blackout',
		label: 'General - Blackout',
		channel: 0,
		number: 1,
		velocity: 82,
		enum: 'Blackout',
	},
	{
		id: 'Midi Only__Log received and processed Midi events',
		label: 'Midi Only - Log received and processed Midi events',
		channel: 0,
		number: 1,
		velocity: 119,
		enum: 'MidiLog',
	},
	{
		id: 'Midi Only__Midi Feedback',
		label: 'Midi Only - Midi Feedback',
		channel: 0,
		number: 1,
		velocity: 120,
		enum: 'MidiFeedback',
	},

	// LOGICAL
	{
		id: 'Activation__Section Enabled',
		label: 'Activation - Section Enabled',
		channel: 0,
		number: 37,
		velocity: 64,
		enum: 'SectionEnabled',
		isLogical: true,
	},
	{
		id: 'Activation__Spot Enabled',
		label: 'Activation - Spot Enabled',
		channel: 0,
		number: 37,
		velocity: 96,
		enum: 'SpotEnabled',
		isLogical: true,
	},
	{
		id: 'Activation__Wash Enabled',
		label: 'Activation - Wash Enabled',
		channel: 0,
		number: 38,
		velocity: 0,
		enum: 'WashEnabled',
		isLogical: true,
	},
	{
		id: 'Effect__Laser Enabled',
		label: 'Effect - Laser Enabled',
		channel: 0,
		number: 38,
		velocity: 32,
		enum: 'LaserEnabled',
		isLogical: true,
	},
	{
		id: 'General__Gobo Spin Speed Reverse',
		label: 'General - Gobo Spin Speed Reverse',
		channel: 0,
		number: 44,
		velocity: 32,
		enum: 'GoboSpinSpeedReverse',
		isLogical: true,
	},
]

export default toggles
