import type { MappingData } from './mapping_data.js'

export const toggles: MappingData[] = [
	{
		id: 'Advanced__Section Floor',
		label: 'Advanced - Section Floor',
		channel: 0,
		number: 0,
		velocity: 0,
		type: 'single',
		isLogical: false,
		enum: 'SectionToggles',
		class: 'physical',
	},
	{
		id: 'Advanced__Section Dancer Podium',
		label: 'Advanced - Section Dancer Podium',
		channel: 0,
		number: 0,
		velocity: 1,
		type: 'single',
		isLogical: false,
		enum: 'SectionToggles',
		class: 'physical',
	},
	{
		id: 'Advanced__Section Screen Bottom',
		label: 'Advanced - Section Screen Bottom',
		channel: 0,
		number: 0,
		velocity: 2,
		type: 'single',
		isLogical: false,
		enum: 'SectionToggles',
		class: 'physical',
	},
	{
		id: 'Advanced__Section Screen Side',
		label: 'Advanced - Section Screen Side',
		channel: 0,
		number: 0,
		velocity: 3,
		type: 'single',
		isLogical: false,
		enum: 'SectionToggles',
		class: 'physical',
	},
	{
		id: 'Advanced__Section Screen Top',
		label: 'Advanced - Section Screen Top',
		channel: 0,
		number: 0,
		velocity: 4,
		type: 'single',
		isLogical: false,
		enum: 'SectionToggles',
		class: 'physical',
	},
	{
		id: 'Advanced__Section In Screen',
		label: 'Advanced - Section In Screen',
		channel: 0,
		number: 0,
		velocity: 5,
		type: 'single',
		isLogical: false,
		enum: 'SectionToggles',
		class: 'physical',
	},
	{
		id: 'Advanced__Section Mirror Ball Inner',
		label: 'Advanced - Section Mirror Ball Inner',
		channel: 0,
		number: 0,
		velocity: 6,
		type: 'single',
		isLogical: false,
		enum: 'SectionToggles',
		class: 'physical',
	},
	{
		id: 'Advanced__Section Mirror Ball Outer',
		label: 'Advanced - Section Mirror Ball Outer',
		channel: 0,
		number: 0,
		velocity: 7,
		type: 'single',
		isLogical: false,
		enum: 'SectionToggles',
		class: 'physical',
	},
	{
		id: 'Advanced__Section Side Screen Top',
		label: 'Advanced - Section Side Screen Top',
		channel: 0,
		number: 0,
		velocity: 8,
		type: 'single',
		isLogical: false,
		enum: 'SectionToggles',
		class: 'physical',
	},
	{
		id: 'Advanced__Section Side Screen Bottom',
		label: 'Advanced - Section Side Screen Bottom',
		channel: 0,
		number: 0,
		velocity: 9,
		type: 'single',
		isLogical: false,
		enum: 'SectionToggles',
		class: 'physical',
	},
	{
		id: 'Macro__Bypass Apply',
		label: 'Macro - Bypass Apply',
		channel: 0,
		number: 0,
		velocity: 44,
		type: 'single',
		isLogical: false,
		enum: 'MacroBypassApply',
		class: 'physical',
	},
	{
		id: 'Macro__Apply Manually',
		label: 'Macro - Apply Manually',
		channel: 0,
		number: 0,
		velocity: 45,
		type: 'single',
		isLogical: false,
		enum: 'MacroApplyManually',
		class: 'physical',
	},
	{
		id: 'Macro__Set Macro Toggle',
		label: 'Macro - Set Macro Toggle',
		channel: 0,
		number: 0,
		velocity: 46,
		type: 'single',
		isLogical: false,
		enum: 'MacroSet',
		class: 'physical',
	},
	{
		id: 'Advanced__Side Left',
		label: 'Advanced - Side Left',
		channel: 0,
		number: 0,
		velocity: 111,
		type: 'single',
		isLogical: false,
		enum: 'SideToggles',
		class: 'global',
	},
	{
		id: 'Advanced__Side Right',
		label: 'Advanced - Side Right',
		channel: 0,
		number: 0,
		velocity: 112,
		type: 'single',
		isLogical: false,
		enum: 'SideToggles',
		class: 'global',
	},
	{
		id: 'Activation__Section Enabled',
		label: 'Activation - Section Enabled',
		channel: 0,
		number: 1,
		velocity: 0,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'Activation__Spot Enabled',
		label: 'Activation - Spot Enabled',
		channel: 0,
		number: 1,
		velocity: 1,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'Activation__Wash Enabled',
		label: 'Activation - Wash Enabled',
		channel: 0,
		number: 1,
		velocity: 2,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'Effect__Laser Enabled',
		label: 'Effect - Laser Enabled',
		channel: 0,
		number: 1,
		velocity: 3,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'General__Set Value to Color (for Color Buttons)',
		label: 'General - Set Value to Color (for Color Buttons)',
		channel: 0,
		number: 1,
		velocity: 21,
		type: 'single',
		isLogical: false,
		enum: 'SetColor',
		class: 'physical',
	},
	{
		id: 'General__Set Spot Color',
		label: 'General - Set Spot Color',
		channel: 0,
		number: 1,
		velocity: 22,
		type: 'single',
		isLogical: false,
		enum: 'SetColor',
		class: 'physical',
	},
	{
		id: 'General__Set Wash Color',
		label: 'General - Set Wash Color',
		channel: 0,
		number: 1,
		velocity: 23,
		type: 'single',
		isLogical: false,
		enum: 'SetColor',
		class: 'physical',
	},
	{
		id: 'General__Set Laser Color',
		label: 'General - Set Laser Color',
		channel: 0,
		number: 1,
		velocity: 24,
		type: 'single',
		isLogical: false,
		enum: 'SetColor',
		class: 'physical',
	},
	{
		id: 'General__Gobo Spin Speed Reverse',
		label: 'General - Gobo Spin Speed Reverse',
		channel: 0,
		number: 1,
		velocity: 48,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'physical',
	},
	{
		id: 'Advanced__Allow Portals',
		label: 'Advanced - Allow Portals',
		channel: 0,
		number: 1,
		velocity: 58,
		type: 'single',
		isLogical: false,
		enum: 'AllowPortals',
		class: 'global',
	},
	{
		id: 'Advanced__Clean Light',
		label: 'Advanced - Clean Light',
		channel: 0,
		number: 1,
		velocity: 59,
		type: 'single',
		isLogical: false,
		enum: 'CleanLight',
		class: 'global',
	},
	{
		id: 'Advanced__Very Poor Sign',
		label: 'Advanced - Very Poor Sign',
		channel: 0,
		number: 1,
		velocity: 60,
		type: 'single',
		isLogical: false,
		enum: 'VeryPoorSign',
		class: 'global',
	},
	{
		id: 'Advanced__RESERVED',
		label: 'Advanced - RESERVED',
		channel: 0,
		number: 1,
		velocity: 61,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'global',
	},
	{
		id: 'Activation__Disco Ball',
		label: 'Activation - Disco Ball',
		channel: 0,
		number: 1,
		velocity: 62,
		type: 'single',
		isLogical: false,
		enum: 'DiscoBall',
		class: 'global',
	},
	{
		id: 'Activation__Mirror Ball Inner',
		label: 'Activation - Mirror Ball Inner',
		channel: 0,
		number: 1,
		velocity: 63,
		type: 'single',
		isLogical: false,
		enum: 'MirrorBallInner',
		class: 'global',
	},
	{
		id: 'Activation__Mirror Ball Middle',
		label: 'Activation - Mirror Ball Middle',
		channel: 0,
		number: 1,
		velocity: 64,
		type: 'single',
		isLogical: false,
		enum: 'MirrorBallMiddle',
		class: 'global',
	},
	{
		id: 'Activation__Mirror Ball Outer',
		label: 'Activation - Mirror Ball Outer',
		channel: 0,
		number: 1,
		velocity: 65,
		type: 'single',
		isLogical: false,
		enum: 'MirrorBallOuter',
		class: 'global',
	},
	{
		id: 'General__Blackout',
		label: 'General - Blackout',
		channel: 0,
		number: 1,
		velocity: 82,
		type: 'single',
		isLogical: false,
		enum: 'Blackout',
		class: 'global',
	},
	{
		id: 'Midi Only__Log received and processed Midi events',
		label: 'Midi Only - Log received and processed Midi events',
		channel: 0,
		number: 1,
		velocity: 119,
		type: 'single',
		isLogical: false,
		enum: 'MidiLog',
		class: 'midi',
	},
	{
		id: 'Midi Only__Midi Feedback',
		label: 'Midi Only - Midi Feedback',
		channel: 0,
		number: 1,
		velocity: 120,
		type: 'single',
		isLogical: false,
		enum: 'MidiFeedback',
		class: 'midi',
	},
	{
		id: 'General__Gobo Spin Speed Reverse',
		label: 'General - Gobo Spin Speed Reverse',
		channel: 0,
		number: 1,
		velocity: 122,
		type: 'single',
		isLogical: false,
		enum: null,
		class: 'physical',
	},
	{
		id: 'Activation__Section Enabled',
		label: 'Activation - Section Enabled',
		channel: 0,
		number: 37,
		velocity: 64,
		type: 'ranged',
		isLogical: true,
		enum: 'SectionEnabled',
		class: 'logical',
		range: {
			variable: 'velocity',
			start: 64,
			end: 95,
		},
	},
	{
		id: 'Activation__Spot Enabled',
		label: 'Activation - Spot Enabled',
		channel: 0,
		number: 37,
		velocity: 96,
		type: 'ranged',
		isLogical: true,
		enum: 'SpotEnabled',
		class: 'logical',
		range: {
			variable: 'velocity',
			start: 96,
			end: 127,
		},
	},
	{
		id: 'Activation__Wash Enabled',
		label: 'Activation - Wash Enabled',
		channel: 0,
		number: 38,
		velocity: 0,
		type: 'ranged',
		isLogical: true,
		enum: 'WashEnabled',
		class: 'logical',
		range: {
			variable: 'velocity',
			start: 0,
			end: 31,
		},
	},
	{
		id: 'Effect__Laser Enabled',
		label: 'Effect - Laser Enabled',
		channel: 0,
		number: 38,
		velocity: 32,
		type: 'ranged',
		isLogical: true,
		enum: 'LaserEnabled',
		class: 'logical',
		range: {
			variable: 'velocity',
			start: 32,
			end: 63,
		},
	},
	{
		id: 'General__Gobo Spin Speed Reverse',
		label: 'General - Gobo Spin Speed Reverse',
		channel: 0,
		number: 44,
		velocity: 32,
		type: 'ranged',
		isLogical: true,
		enum: 'GoboSpinSpeedReverse',
		class: 'logical',
		range: {
			variable: 'velocity',
			start: 32,
			end: 63,
		},
	},
] as const

export default toggles
